/**
 * @color-literals. An on-photo line carries two colours measured against its one
 * photograph; they do not change with the theme any more than the photograph does.
 */
/**
 * GENERATED by mag-send from the magazine draft "DEV - Shanyin Qiwu (story)".
 * Do not edit by hand: change the draft in the vault and send it again
 * (see src/pages/read/conversation/magSend.ts). Page facts such as the title,
 * byline and credit live in the hand-written piece file beside this one.
 */
import type { ConversationSpec, Shot } from '../spec';

export const shots = {
  portrait: { slot: "portrait", file: "portrait.jpg", alt: "Yan Jinwen seated in his studio", y: 0.4 },
  classTable: { slot: "class-table", file: "class-at-the-table.jpg", alt: "Adrian at the repair table during the class, seen through the studio window", y: 0.4 },
  goldSeam: { slot: "gold-seam", file: "gold-seam-bowl.jpg", alt: "A dark bowl with a gold seam along its rim" },
  cupOnWood: { slot: "cup-on-wood", file: "cup-on-wood.jpg", alt: "An old cup on wood" },
  jar: { slot: "jar", file: "jar-in-hand.jpg", alt: "A hand turning an old glazed jar with a repaired rim" },
  stapledLid: { slot: "stapled-lid", file: "stapled-lid.jpg", alt: "A lid mended with staples" },
  stapledBowl: { slot: "stapled-bowl", file: "stapled-bowl.jpg", alt: "A bowl mended with a row of staples" },
  shelves: { slot: "shelves", file: "display-shelves.jpg", alt: "Repaired cups and jars displayed on open shelves" },
  kettle: { slot: "kettle", file: "kettle-over-charcoal.jpg", alt: "An iron kettle steaming over a charcoal stove, calligraphy behind" },
  classCupAndDish: { slot: "class-cup-and-dish", file: "class-cup-and-dish.jpg", alt: "A cup and dish at the repair class" },
  liningHand: { slot: "lining-hand", file: "lining-in-hand.jpg", alt: "Hands shaping the metal lining of a green cup" },
  liningClose: { slot: "lining-close", file: "lining-close.jpg", alt: "The metal lining of a cup, close" },
  classCup: { slot: "class-cup", file: "class-at-the-cup.jpg", alt: "Adrian at the class, working a cup" },
  whiteBowl: { slot: "white-bowl", file: "white-footed-bowl.jpg", alt: "One white footed bowl in the dark" },
  mendedDish: { slot: "mended-dish", file: "teapot-on-mended-dish.jpg", alt: "A teapot on a mended dish beside a cup of tea" },
  goldDish: { slot: "gold-dish", file: "teapot-on-gold-dish.jpg", alt: "A teapot on a gold-mended dish" },
  stream: { slot: "stream", file: "by-the-stream.jpg", alt: "Sitting on the rocks beside a stream" },
  pouring: { slot: "pouring", file: "pouring.jpg", alt: "Tea being poured" },
  settingCups: { slot: "setting-cups", file: "setting-cups.jpg", alt: "Hands setting out cups at the tea table" },
  listening: { slot: "listening", file: "listening.jpg", alt: "Listening at the tea table, hand at his chin" },
  courtyard: { slot: "courtyard", file: "courtyard-table.jpg", alt: "A tea table in the courtyard" },
  studio: { slot: "studio", file: "studio-table.jpg", alt: "The studio table by candlelight, cups, bowls and pots laid out" },
  classBench: { slot: "class-bench", file: "class-at-the-bench.jpg", alt: "Adrian at the workbench, working a cup" },
  goldBowl: { slot: "gold-bowl", file: "gold-mended-bowl.jpg", alt: "A dark tea bowl with gold repair lines, alone on a pale ground", y: 1 },
  lastBowl: { slot: "last-bowl", file: "stapled-bowl-grasses.jpg", alt: "A stapled tea bowl on a dark shelf, dry grasses lit behind it" },
} satisfies Record<string, Shot>;

export const story: Pick<ConversationSpec, 'portrait' | 'intro' | 'hook' | 'opening' | 'parts' | 'ending' | 'closing'> = {
  portrait: shots.portrait,
  intro: "At the base of the Wuyi Mountains, I found my way into this shop where I just loved everything. Everything was taken care of at such a high level. Everywhere I looked, each and every piece was cared for immaculately, using skills that have been developed over many years. The first time I came here, I did not have time to learn, but the second time I created space in my schedule to pick up some of the skills and spend more time with this master.",
  hook: "Nine out of ten old things are damaged. But I think these are ==all marks of history.==",
  opening: [
    { kind: "n", id: "o-n1", text: "Yan Jinwen mends old tea ware with lacquer. It began with tea." },
  ],
  parts: [
    {
      title: "Marks of history",
      blocks: [
        {
          kind: "a",
          id: "p1-a1",
          text: "First of all, I quite like collecting things. Because of tea, I like to collect some tea-related utensils. Many old utensils have some damages here and there.",
        },
        {
          kind: "a",
          id: "p1-a2",
          text: "After I repair them, they couldn’t be used before the repair, but after repair, they can return to our lives. Some utensils may be a hundred years old, and some may be a thousand years old. Just think about it, it’s a very wonderful thing that they can meet you after thousands of years. And it’s very meaningful that they can continue to be with us now, on our tea tables or in our lives.",
        },
        {
          kind: "a",
          id: "p1-a3",
          text: "So, I don’t think it’s about inspiration. It’s just that my love for these utensils themselves naturally makes me find various ways to enable them to be better passed on and better used.",
        },
        {
          kind: "photos",
          shots: [
            shots.goldSeam,
            shots.cupOnWood,
          ],
          stagger: true,
        },
        { kind: "n", id: "p1-n1", text: "Plenty of tea drinkers are happy with a new gaiwan. He doesn’t argue with them." },
        {
          kind: "a",
          id: "p1-a4",
          text: "For instance, some people like coffee, while others like tea. I think we can only do what we like in the present, and through this, attract like-minded friends.",
        },
        {
          kind: "side",
          shot: shots.jar,
          blocks: [
            { kind: "a", id: "p1-a5", text: "I like them because I think they have a more natural sense of historical vicissitudes." },
            {
              kind: "a",
              id: "p1-l2",
              text: "Moreover, I can feel the state of the people who created them at that time through touching these utensils.",
            },
          ],
          flip: true,
        },
        {
          kind: "glyph",
          glyph: "缘分",
          blocks: [
            {
              kind: "q",
              id: "p1-q1",
              text: "Some people talk about karma, how old things carry a weight with them. By bringing these old things back to life, do you feel you are honoring the past?",
            },
            { kind: "a", id: "p1-l3", text: "This feeling is very subtle, and I can’t quite put it into words." },
            {
              kind: "a",
              id: "p1-a6",
              text: "It’s probably a kind of fate, 缘分. First, I’ve mastered this repair technique, and then I’ve come to love these ancient ceramics. It’s probably some kind of fate.",
            },
          ],
        },
      ],
      opener: shots.classTable,
    },
    {
      title: "People cherished utensils more",
      blocks: [
        { kind: "a", id: "p2-a1", text: "Repair techniques have existed for thousands of years." },
        {
          kind: "side",
          shot: shots.stapledBowl,
          blocks: [
            { kind: "a", id: "p2-l1", text: "In the past, people cherished utensils more." },
            {
              kind: "a",
              id: "p2-a2",
              text: "Many utensils in daily life that got damaged can still show traces of repair. This technique was quite common in ancient times. On the contrary, in our current society, it’s not as popular because we can easily buy new things.",
            },
            {
              kind: "a",
              id: "p2-a3",
              text: "For example, the repair of cracked porcelain using staples can be traced back to the Song Dynasty, with a history of more than 1,000 years.",
            },
          ],
        },
        { kind: "n", id: "p2-n1", text: "He takes the mended pieces out to exhibitions and markets, where people meet them for the first time." },
        {
          kind: "a",
          id: "p2-a4",
          text: "When these artifacts are in a damaged state, people don’t know what they can be used for. But when I repair them, people discover, ‘Oh, this thing can be used like this, it’s quite interesting.’",
        },
        { kind: "wide", shot: shots.shelves, aspect: "4/5", narrow: true, offset: "right" },
        {
          kind: "a",
          id: "p2-a5",
          text: "It’s the state of being dedicated to excelling at something. The ancients focused more on pursuing form, spirit, and inner expression. Nowadays, this is somewhat lacking.",
        },
      ],
      opener: shots.stapledLid,
    },
    {
      title: "Restoration can’t be rushed",
      blocks: [
        { kind: "a", id: "p3-a1", text: "It’s about slowing down, devoting more energy to the thing itself." },
        {
          kind: "line",
          id: "p3-l1",
          text: "Restoration ==can’t be rushed.==",
          size: "xl",
          follow: { id: "p3-a2", text: "It requires time to polish slowly to produce a good result." },
        },
        { kind: "wide", shot: shots.classCupAndDish, aspect: "4/5", narrow: true, offset: "right" },
        {
          kind: "photos",
          shots: [
            shots.liningHand,
            shots.liningClose,
          ],
        },
        {
          kind: "side",
          shot: shots.classCup,
          blocks: [
            {
              kind: "a",
              id: "p3-a3",
              text: "I think the main thing is being able to calm oneself down, slow down, and truly focus one’s energy on _a single utensil or a single matter._ It has made my life more steady and relaxed.",
            },
            { kind: "n", id: "p3-n1", text: "The friends who take a mended piece home find something of the same." },
            { kind: "a", id: "p3-a5", text: "Then they realize it helps them calm down and focus more on the present moment." },
          ],
          flip: true,
        },
        { kind: "wide", shot: shots.whiteBowl },
        {
          kind: "photos",
          shots: [
            shots.mendedDish,
            shots.goldDish,
          ],
          stagger: true,
        },
      ],
      opener: shots.kettle,
    },
    {
      title: "An invisible language",
      blocks: [
        {
          kind: "a",
          id: "p4-a1",
          text: "Tea is an indispensable spiritual food in my life. Like a craft, it allows me to focus on the present moment, which is of great significance to me.",
        },
        { kind: "wide", shot: shots.pouring, aspect: "4/5", narrow: true, offset: "left" },
        {
          kind: "line",
          id: "p4-l1",
          text: "Tea is like an ==invisible language.==",
          size: "xl",
          follow: {
            id: "p4-a2",
            text: "Just like us, from different countries, but we can sit together because of tea. Maybe the topic isn’t tea, but it brings us together.",
          },
        },
        {
          kind: "photos",
          shots: [
            shots.settingCups,
            shots.listening,
          ],
          stagger: true,
        },
        {
          kind: "side",
          shot: shots.courtyard,
          blocks: [
            { kind: "n", id: "p4-n1", text: "The name over the door came from the lacquer, and he wears it lightly." },
            { kind: "a", id: "p4-a3", text: "It doesn’t have too many specific meanings, it’s just like a nickname." },
          ],
          flip: true,
        },
        { kind: "wide", shot: shots.studio },
        {
          kind: "n",
          id: "p4-n2",
          text: "His plan now is to teach what he knows, in paid courses, so more people can learn and help preserve the craft.",
        },
        {
          kind: "side",
          shot: shots.classBench,
          blocks: [
            {
              kind: "n",
              id: "p4-q1",
              text: "One thing I realized a long time ago is if I hide my skills or my ways of doing things, it will end with me.",
            },
            { kind: "a", id: "p4-a4", text: "We must first get our own lives in order, then we can have better energy to spread meaningful things." },
          ],
          flip: true,
        },
      ],
      opener: shots.stream,
    },
  ],
  ending: {
    blocks: [
      { kind: "a", id: "e-a1", text: "A broken object is like life. Life can’t be perfect, and neither can objects." },
      {
        kind: "on-photo",
        id: "e-on",
        shot: shots.goldBowl,
        text: "When we repair objects, we are also ==repairing ourselves.==",
        ink: "#1c1712",
        accent: "#5a4318",
        aspect: "4/5",
      },
      {
        kind: "a",
        id: "e-a2",
        text: "We all have shortcomings; we identify problems, adjust them, and solve them. It’s the same with objects. Life is not afraid of difficulties. When facing them, find ways to solve them and embrace a new state of life. The saying I like is:",
      },
    ],
    saying: { id: "e-saying", text: "“The world is tattered, but we are still ==mending it.==”" },
    shot: shots.lastBowl,
    aspect: "1080/1618",
  },
  closing: "Leaving this place, I felt a strong sense of the love and attention that goes into these things that we do regularly. How true, and how clearly I can see: how you do it in one place, you do it in every place. Beyond the love for those things which are old, it is about putting energy into those things which you cherish, and bringing them a new life.",
};
