// Generated by scripts/export-wisdom-dataset.mjs. Do not edit by hand.
//
// What the public dataset in public/wisdom is, and when it was built. The
// reference reads these to say so on the front door and to print a citation
// that names a version.

export const DATASET_VERSION = '1.0.0';

/** ISO date the export last ran. */
export const DATASET_BUILT = '2026-07-27';

/** One file per record, across every holding. */
export const DATASET_RECORDS = 629;
