/* This file is generated by scripts/tea-reference-markdown/build-pages.mjs. */
import type { TeaReferencePageRegistry } from './types';

export const GENERATED_TEA_REFERENCE_REGISTRY = {
  "schemaVersion": 1,
  "pages": [
    {
      "id": "greater-yiwu",
      "slug": "greater-yiwu",
      "kind": "tea_area",
      "label": "Greater Yiwu",
      "nativeName": "易武",
      "parentId": "yunnan",
      "sourceIds": [
        "teadb-greater-yiwu"
      ],
      "sections": [
        {
          "key": "scope",
          "label": "A name at several scales",
          "text": "Yiwu can mean a township, a market center, or a much broader tea area in eastern Xishuangbanna. In trade, the name often reaches beyond the town itself, so a Yiwu label should be read as a regional claim whose scale still needs context.",
          "sourceIds": [
            "teadb-greater-yiwu"
          ]
        },
        {
          "key": "common-character",
          "label": "Shared reputation, varied tea",
          "text": "Greater Yiwu is often associated with a softer opening and a persistent sweet return when compared with the more forceful profiles linked to western Xishuangbanna. The area contains many growing places, however, and their material can vary substantially; this is a regional tendency, not a tasting promise for an individual tea.",
          "sourceIds": [
            "teadb-greater-yiwu"
          ]
        },
        {
          "key": "history",
          "label": "Trade history",
          "text": "Yiwu became an important collection and distribution point for tea from the old Six Famous Tea Mountains. Its trade connected local leaf, merchant networks, tribute routes, and later some of the best-known early twentieth-century tea firms.",
          "sourceIds": [
            "teadb-greater-yiwu"
          ]
        }
      ]
    },
    {
      "id": "lincang",
      "slug": "lincang",
      "kind": "major_region",
      "label": "Lincang",
      "nativeName": "临沧",
      "parentId": "yunnan",
      "sourceIds": [
        "teadb-lincang"
      ],
      "sections": [
        {
          "key": "scope",
          "label": "Northern Pu’er country",
          "text": "Lincang lies north of Pu’er Prefecture and against Myanmar to the west. Its tea geography includes Mengku, Yongde, Fengqing, Bangdong, Bingdao, and Xigui, with repeated place names such as Daxueshan making precise labels especially important.",
          "sourceIds": [
            "teadb-lincang"
          ]
        },
        {
          "key": "common-character",
          "label": "A broad regional tendency",
          "text": "Young single-origin Lincang sheng is often described as green, firm, and bitter. This reputation is useful as a starting point only: Lincang is a large prefecture, and material from its counties, mountains, and villages should not be collapsed into one tasting profile.",
          "sourceIds": [
            "teadb-lincang"
          ]
        },
        {
          "key": "history",
          "label": "History beyond single origins",
          "text": "Lincang has a smaller public archive of famous aged single-origin teas than Yiwu or Menghai. Older blended productions, especially those associated with Xiaguan, nevertheless provide a historical thread, even when the exact origin of their base material cannot be reconstructed.",
          "sourceIds": [
            "teadb-lincang"
          ]
        }
      ]
    },
    {
      "id": "menghai-county",
      "slug": "menghai-county",
      "kind": "tea_area",
      "label": "Menghai County",
      "nativeName": "勐海县",
      "parentId": "yunnan",
      "sourceIds": [
        "teadb-menghai-county"
      ],
      "sections": [
        {
          "key": "scope",
          "label": "Western Xishuangbanna",
          "text": "Menghai County anchors much of western Xishuangbanna’s Pu’er landscape. Names such as Nannuo, Bulang, Mengsong, Hekai, Pasha, and Bada describe distinct mountain areas within the county rather than interchangeable synonyms for Menghai.",
          "sourceIds": [
            "teadb-menghai-county"
          ]
        },
        {
          "key": "common-character",
          "label": "A forceful reputation",
          "text": "Specialist writing often contrasts Menghai’s strength and bitterness with the gentler reputation of eastern Xishuangbanna. That comparison is a broad regional convention: tree material, craft, blend, age, and storage still create large differences within the county.",
          "sourceIds": [
            "teadb-menghai-county"
          ]
        },
        {
          "key": "history",
          "label": "Factory-era importance",
          "text": "The establishment of Menghai Tea Factory and the post-1950 shift toward large-scale production made the county central to twentieth-century Pu’er. Regional leaf increasingly entered factory blends, connecting Menghai with many benchmark raw and ripe productions.",
          "sourceIds": [
            "teadb-menghai-county"
          ]
        }
      ]
    },
    {
      "id": "puer",
      "slug": "puer",
      "kind": "tea_family",
      "label": "Pu’er",
      "nativeName": "普洱茶",
      "sourceIds": [
        "ctma-puer-history-2021"
      ],
      "sections": [
        {
          "key": "identity",
          "label": "A tea rooted in Yunnan",
          "text": "Pu’er belongs to Yunnan’s long tea history. The name now gathers a family of teas whose identity is tied not only to manufacture, but also to material, place, and the traditions that developed around them.",
          "sourceIds": [
            "ctma-puer-history-2021"
          ]
        },
        {
          "key": "history",
          "label": "Trade and continuity",
          "text": "Tea moved from Yunnan toward Tibet and farther markets along trading networks that are often grouped under the Tea Horse Road. That commerce supported mountain production, market towns, and enduring links between tea-growing communities and distant drinkers.",
          "sourceIds": [
            "ctma-puer-history-2021"
          ]
        },
        {
          "key": "modern-family",
          "label": "The modern family",
          "text": "Modern Pu’er includes sheng and shou. Their processing paths differ, but both sit within a twentieth-century industry that restored tea gardens, expanded production, and developed distinct forms for domestic and export markets.",
          "sourceIds": [
            "ctma-puer-history-2021"
          ]
        }
      ]
    },
    {
      "id": "sheng",
      "slug": "sheng",
      "kind": "tea_type",
      "label": "Sheng Pu’er",
      "nativeName": "生普洱",
      "parentId": "puer",
      "sourceIds": [
        "marshaln-young-puer-2013",
        "teaguardian-raw-cooked-puer"
      ],
      "sections": [
        {
          "key": "identity",
          "label": "What sheng means",
          "text": "Sheng is the undarkened branch of Pu’er, often called raw Pu’er in English. The label distinguishes it from shou, whose accelerated post-fermentation creates a markedly different tea from the outset.",
          "sourceIds": [
            "teaguardian-raw-cooked-puer"
          ]
        },
        {
          "key": "processing",
          "label": "From maocha to finished tea",
          "text": "Maocha names an intermediate state in tea production, while sheng describes the tea as it reaches the drinker. Sheng material may be sorted, dried, left loose, or steamed and compressed; the two terms overlap, but they describe the tea from different viewpoints.",
          "sourceIds": [
            "teaguardian-raw-cooked-puer"
          ]
        },
        {
          "key": "aging",
          "label": "Change through storage",
          "text": "Sheng is not given shou’s rapid fermentation. Its character instead changes gradually during storage, with leaf, liquor, aroma, and texture developing over years. Storage conditions therefore belong to the tea’s history, not as a guarantee of quality but as part of how any particular cake has evolved.",
          "sourceIds": [
            "marshaln-young-puer-2013"
          ]
        }
      ]
    },
    {
      "id": "yunnan",
      "slug": "yunnan",
      "kind": "major_region",
      "label": "Yunnan Pu’er Regions",
      "nativeName": "云南",
      "sourceIds": [
        "teadb-yunnan-overview"
      ],
      "sections": [
        {
          "key": "geographic-frame",
          "label": "The geographic frame",
          "text": "Pu’er is unusually place-bound for a broad tea family. Yunnan is the central geographic frame, while comparable processing outside the province does not by itself make a tea Yunnan Pu’er.",
          "sourceIds": [
            "teadb-yunnan-overview"
          ]
        },
        {
          "key": "regional-map",
          "label": "A map of regions",
          "text": "Reference maps commonly begin with Xishuangbanna, Pu’er Prefecture, and Lincang, then move toward counties, mountain areas, villages, and local names. Xishuangbanna is often divided into eastern and western tea areas, while other production extends through Yunnan beyond those best-known centers.",
          "sourceIds": [
            "teadb-yunnan-overview"
          ]
        },
        {
          "key": "reading-labels",
          "label": "Read labels with care",
          "text": "Regional schemes are editorial aids rather than a single settled ladder. Boundaries, spellings, and the prominence given to one place over another vary, and famous names also function as commercial language. A place label is useful context, not proof of a tea’s exact origin.",
          "sourceIds": [
            "teadb-yunnan-overview"
          ]
        }
      ]
    }
  ],
  "sources": [
    {
      "sourceId": "ctma-puer-history-2021",
      "publisher": "China Tea Marketing Association",
      "publisherRoleLabel": "Trade association",
      "title": "A millennium in one leaf: a history of Yunnan Pu'er tea",
      "author": "Guangming Daily",
      "publishedDate": "2021-11-17",
      "url": "https://www.ctma.com.cn/hangyeyaowen/71820.html"
    },
    {
      "sourceId": "marshaln-young-puer-2013",
      "publisher": "A Tea Addict's Journal",
      "publisherRoleLabel": "Community",
      "title": "Really young puerh is not really puerh",
      "author": "MarshalN",
      "publishedDate": "2013-09-18",
      "url": "https://marshaln.com/2013/09/really-young-puerh-is-not-really-puerh/"
    },
    {
      "sourceId": "teadb-greater-yiwu",
      "publisher": "TeaDB",
      "publisherRoleLabel": "Specialist editorial",
      "title": "Pu'erh Regions: Eastern Xishuangbanna, Mengla County, Yiwu and Youle",
      "author": "James",
      "publishedDate": "2014-09-13",
      "url": "https://teadb.org/mengla-county-yiwu/"
    },
    {
      "sourceId": "teadb-lincang",
      "publisher": "TeaDB",
      "publisherRoleLabel": "Specialist editorial",
      "title": "Pu'erh Regions: Lincang",
      "author": "James",
      "publishedDate": "2015-02-07",
      "url": "https://teadb.org/lincang/"
    },
    {
      "sourceId": "teadb-menghai-county",
      "publisher": "TeaDB",
      "publisherRoleLabel": "Specialist editorial",
      "title": "Pu'erh Regions: Western Xishuangbanna, Menghai County",
      "author": "James",
      "publishedDate": "2014-10-11",
      "url": "https://teadb.org/menghai-county/"
    },
    {
      "sourceId": "teadb-yunnan-overview",
      "publisher": "TeaDB",
      "publisherRoleLabel": "Specialist editorial",
      "title": "Pu'erh Regions: Yunnan Overview",
      "author": "James",
      "publishedDate": "2014-12-27",
      "url": "https://teadb.org/yunnan/"
    },
    {
      "sourceId": "teaguardian-raw-cooked-puer",
      "publisher": "Tea Guardian",
      "publisherRoleLabel": "Specialist editorial",
      "title": "Raw Puer or Cooked Puer?",
      "author": "Leo Kwan",
      "publishedDate": "",
      "url": "https://www.teaguardian.com/what-is-tea/raw-puer-or-cooked-puer/"
    }
  ]
} as const satisfies TeaReferencePageRegistry;

export const GENERATED_TEA_REFERENCE_PAGES = GENERATED_TEA_REFERENCE_REGISTRY.pages;
