import { ContentType } from '../../types';
import { ReadableStory } from '../../types/read';
import { PEOPLE } from '../people';

export const darkModeProcess: ReadableStory = {
  id: 'template-dark-process',
  type: ContentType.Article,
  status: 'published',
  title: 'Dark Mode Process Feature',
  subtitle: 'The Midnight Kiln',
  thumbnailUrl: 'https://picsum.photos/800/1200?random=dk100',
  durationOrTime: '22 Pages',
  origin: 'In-house',
  description: 'A richly atmospheric article using dark mode to explore the nocturnal world of traditional kiln firing.',
  tags: ['Pottery', 'Teaware', 'Process'],
  content: [
    ":::COVER_MAIN:::$$dark$$Dark Mode Process Feature|The Midnight Kiln|https://picsum.photos/800/1200?random=dk101",
    ":::TEXT_DROP_CAP:::$$dark$$The fire begins at dusk. Not because tradition demands it — though tradition does — but because the kiln must reach peak temperature in the dead of night, when the air is coolest and the draft pulls strongest through the chamber. Master Lin stands at the mouth of the anagama, a forty-foot tunnel of brick and earth that has been loaded over the past three days with two hundred pieces of raw stoneware. The firebox is stacked with split pine, aged for two years in an open shed. He strikes a match, touches it to a twist of newspaper stuffed between the bottom logs, and steps back. The flame catches. A thin column of white smoke rises from the chimney at the far end. The seventy-two-hour firing cycle has begun. For the next three days and three nights, someone must tend this fire without interruption — feeding it, reading it, coaxing it through the slow transformation that will turn raw clay into ceramic, and with luck, into art.",
    ":::IMG_FULL_BLEED:::$$dark$$The anagama kiln at twilight, loaded and sealed|https://picsum.photos/800/1200?random=dk102",
    ":::TEXT_DOUBLE_COL:::$$dark$$The Kiln|The anagama is the oldest continuous-chamber kiln design in East Asian ceramics, introduced to Japan from Korea in the fifth century and refined over the following millennium. Unlike modern electric or gas kilns that offer precise temperature control, the anagama is fired entirely with wood — typically pine or oak — and the results are governed by an unpredictable alchemy of flame path, ash fall, and atmospheric chemistry. No two firings produce identical results. Pieces placed in the same position in consecutive firings will emerge with different surfaces, different colors, different characters. This fundamental uncertainty is not a flaw but the entire point. The anagama potter surrenders control to the fire and accepts whatever the kiln chooses to give.\n\n$$dark$$The Clay|Master Lin works exclusively with local clay dug from a deposit on the hillside above his studio. The clay is rich in iron oxide, which gives it a dark reddish-brown color when raw and an extraordinary range of surface effects when fired to high temperature in a wood kiln. He processes the clay himself — digging, weathering, slaking, screening, wedging — a cycle that takes roughly eighteen months from hillside to studio. 'Commercial clay is dead,' he says flatly. 'It has been processed into uniformity. My clay is alive. It has memory. It remembers the hill it came from, the rain that fell on it, the roots that grew through it. When the fire touches it, those memories surface.'",
    ":::CHAPTER_BOLD:::$$dark$$01|The First Night — Ignition to 400°C",
    ":::IMG_VIGNETTE_SOFT:::$$dark$$Flames lick through the firebox grate in the early hours|https://picsum.photos/800/1200?random=dk103",
    ":::TEXT_SIDEBAR_LEFT:::$$dark$$Water Smoking|The first phase of firing is called water smoking — a slow, careful climb from ambient temperature to roughly 400 degrees Celsius. The goal is to drive all remaining moisture from the clay body without causing steam explosions that would shatter the work. Lin feeds small sticks of kindling into the firebox at measured intervals, never allowing the temperature to rise faster than 50 degrees per hour. Through the spy holes in the kiln wall, the interior glows a dull, barely visible red. The pieces inside are sweating — releasing the chemically bound water that even weeks of air-drying could not remove. Lin monitors the chimney smoke: white means moisture is still escaping; when it turns clear, the first phase is complete. This typically takes twelve to fourteen hours. Lin and his two assistants rotate in four-hour shifts, one person always awake and feeding the fire.|https://picsum.photos/600/800?random=dk104",
    ":::QUOTE_BIG:::$$dark$$Fire does not obey. It negotiates. Every piece of wood is an offer. The kiln decides whether to accept. — Master Lin",
    ":::TEXT_SINGLE_COL:::$$dark$$At two in the morning, the world outside the kiln shed is absolute darkness. The only light comes from the firebox — an orange rectangle that pulses with each new log. Lin's face is lit from below, the shadows carving deep lines around his eyes and mouth. He has not slept. He will not sleep for another sixteen hours. The temperature inside the kiln has reached 600 degrees Celsius — cherry red, visible now through the spy holes as a faint, otherworldly glow. At this temperature, the clay is undergoing a fundamental molecular change called quartz inversion: the crystalline structure of the silica in the clay body is rearranging itself, expanding by roughly two percent. If the temperature rises too quickly during this window, the thermal stress will crack every piece in the kiln. Lin knows this not from a textbook but from the firing he lost twelve years ago, when impatience cost him three months of work. He feeds the fire with deliberate restraint, small pieces of wood laid gently, never thrown.",
    ":::IMG_FILM_STRIP_VERTICAL:::$$dark$$The firing cycle: dusk, midnight, dawn, noon|https://picsum.photos/800/400?random=dk105|https://picsum.photos/800/400?random=dk106|https://picsum.photos/800/400?random=dk107|https://picsum.photos/800/400?random=dk108",
    ":::CHAPTER_BOLD:::$$dark$$02|The Second Day — Climbing to Peak",
    ":::TEXT_DOUBLE_COL:::$$dark$$Body Reduction|By midday on the second day, the temperature has climbed past 900 degrees. Lin shifts his stoking rhythm — larger pieces of wood, fed more frequently, creating bursts of flame that consume all available oxygen inside the chamber. This is reduction firing: by starving the kiln of air, the fire pulls oxygen molecules from the metal oxides in the clay and glaze. Iron oxide loses an oxygen atom and shifts from red to grey or black. Copper oxide transforms from green to a deep, lustrous oxblood red. The smoke thickens and pours from every crack and joint in the kiln structure. The air smells of pitch and carbon and something almost sweet — the volatilized sugars in the pine sap.\n\n$$dark$$Ash Glazing|As the temperature climbs above 1100 degrees, a secondary transformation begins. The pine wood, burning to ash, releases fine particles that are carried by the draft through the entire length of the kiln. This fly ash settles on the surfaces of the pottery, and at these extreme temperatures, the ash melts. Silica and flux in the wood ash combine to form a natural glass — a glaze applied not by human hand but by the fire itself. The thickness and character of this ash glaze depends on placement within the kiln, proximity to the flame path, and the specific mineral content of the wood burned. Pieces nearest the firebox receive the heaviest ash deposits, developing thick, dripping surfaces of amber and olive green. Pieces further back may show only a thin, golden blush.",
    ":::TEXT_SINGLE_COL:::$$dark$$The spy holes become windows into another world. Peering through them with welder's goggles, Lin can see the interior of the kiln glowing a blinding white-yellow. The pottery is incandescent, the same color as the air around it, distinguishable only by the shadows they cast. Pyrometric cones — small pyramids of ceramic material calibrated to bend at specific temperatures — are placed at intervals throughout the kiln. Through the spy holes, Lin watches them: cone 8 has bent, cone 9 is leaning, cone 10 stands straight. When cone 10 bends — indicating a temperature of approximately 1300 degrees Celsius — the peak has been reached. But temperature alone is not the measure. What matters is heat work: the combination of temperature and time that determines the degree of vitrification in the clay body. Lin will hold the kiln at peak temperature for six to eight hours, a sustained effort that requires stoking every three to four minutes with heavy logs.",
    ":::QUOTE_BIG:::$$dark$$The kiln remembers every firing. The walls absorb the ash, the smoke, the heat. Each firing builds on every firing before it. A new kiln produces rough, unpredictable results. An old kiln — a kiln with a hundred firings behind it — produces grace.",
    ":::IMG_FULL_BLEED:::$$dark$$White heat visible through the spy hole at peak temperature|https://picsum.photos/800/1200?random=dk109",
    ":::CHAPTER_BOLD:::$$dark$$03|The Third Night — Descent and Silence",
    ":::TEXT_SINGLE_COL:::$$dark$$The final stoking ends at midnight on the third night. Lin seals the firebox with bricks and clay, plugs the chimney damper, and closes every spy hole with wads of wet newspaper that hiss and steam on contact. The kiln is now a sealed vessel of incandescent air, cooling at its own pace. This cooling phase is as critical as the heating — too rapid a descent and the thermal shock will crack the glaze, creating a defect called dunting. The kiln will take four to five days to cool to a temperature safe for unloading. During this time, there is nothing to do but wait. Lin walks to the farmhouse, drinks a glass of cold water, and sleeps for fourteen hours. When he wakes, the kiln shed is quiet for the first time in three days. The chimney has stopped smoking. The bricks are still too hot to touch. Inside, in the slowly dimming heat, two hundred pieces of pottery are completing their transformation in darkness and silence — the iron settling into its final oxidation state, the ash glaze solidifying into glass, the clay body contracting as it cools, locking in the memory of the fire.",
    ":::TEXT_SIDEBAR_LEFT:::$$dark$$The Unloading|Five days after the final stoking, Lin unseals the kiln door. Even now, the interior is warm — perhaps 50 degrees Celsius, the temperature of a hot bath. He reaches in and lifts out the first piece: a tea bowl, placed in the path of heaviest ash fall. Its surface is extraordinary — a thick, uneven glaze of olive green and amber, with rivulets of melted ash frozen mid-drip. Where the bowl sat on a shell wadding, the bare clay shows through: dark grey from the reduction, with a rough, stony texture. Lin turns it in his hands, holds it up to the light, runs his thumb across the interior. He says nothing for a long moment. Then: 'This one is good.' Not every piece will earn that verdict. Perhaps sixty percent of the load will meet his standard. The rest will be broken with a hammer and returned to the earth.|https://picsum.photos/600/800?random=dk110",
    ":::IMG_FULL_BLEED:::$$dark$$The first bowl emerges from the cooled kiln|https://picsum.photos/800/1200?random=dk111",
    ":::EPILOGUE_CENTERED:::$$dark$$The cycle is complete.\nClay returns to stone.\nAsh becomes glass.\nThe fire's memory lives\nin every surface it touched.\n\nUntil the next firing begins.",
    ":::COPYRIGHT_PAGE:::$$dark$$Words & Photography by Chen Wei\nKiln Master: Lin\n\nTeajia Magazine"
  ],
  author: PEOPLE.chen,
};
