import { ContentType } from '../../types';
import { ReadableStory } from '../../types/read';
import { PEOPLE } from '../people';

export const interviewWithImages: ReadableStory = {
  id: 'template-interview-images',
  type: ContentType.Article,
  status: 'published',
  title: 'Interview with Images',
  subtitle: 'The Tea Farmer',
  thumbnailUrl: 'https://picsum.photos/800/1200?random=iwi001',
  durationOrTime: '25 Pages',
  origin: 'In-house',
  description: 'A portrait-driven interview blending environmental photography with intimate Q&A about life in the tea fields.',
  tags: ['Interview', 'Farming', 'People'],
  category: 'interview',
  content: [
    ":::IMG_FULL_BLEED_TITLE:::Master Zhou Yu — Life in the Wuyi Mountains|https://picsum.photos/800/1200?random=iwi002",

    ":::TEXT_SINGLE_COL:::We arrived at Zhou Yu's workshop in the Wuyi Mountains on a morning so misty that the famous rock formations were invisible until we were standing beneath them. The workshop sits at the base of a cliff in the Zhengyan — the 'correct rock' zone that produces the most prized Yan Cha. Zhou met us at the gate wearing the same clothes he wears every day: a faded blue cotton jacket, canvas pants stained with charcoal dust, and rubber-soled shoes that grip the steep stone paths between his garden terraces. He is sixty-three years old and has been making tea in this exact location for forty-one years. Before him, his father worked these same gardens for thirty-five years. Before that, his grandfather. The workshop is not picturesque in the way that tea marketing materials might suggest — it is a working facility, cluttered with bamboo trays, charcoal baskets, and the accumulated tools of a craft practiced without interruption for three generations.",

    ":::MAGAZINE_INTERVIEW_Q_A:::Chen|Master Zhou, can you describe a typical day during the spring harvest?\n\nZhou|There is no typical day. Every day the mountain gives different conditions and I must respond. But I will describe yesterday. I wake at four-thirty. Before light. I make tea for myself — last year's Rou Gui, the one from the high terrace. I drink three cups standing in the doorway, listening to the mountain. By five-fifteen I can see well enough to walk the garden. I check the leaves — not just looking but touching, smelling, sometimes tasting a raw leaf to judge the amino acid content. By six, if conditions are right, I call the pickers. We have a team of eight women from the village who have worked with me for over twenty years. They know exactly what I need without my saying it.\n\nChen|What do you look for in the morning inspection?\n\nZhou|Three things. First, the dew — how heavy is it, and is it clean dew or does it carry dust from the road? Dusty dew means we wait. Second, the leaf color — has it changed overnight? The buds should be a lighter green than the mature leaves, and the contrast should be sharp. If the contrast is muddy, the bush is stressed and we leave it to recover. Third, the feel. I roll a bud between my fingers. If it squeaks slightly and springs back, it is ready. If it is limp, it has grown too fast overnight and the flavor will be diluted.",

    ":::IMG_FULL_BLEED:::Zhou's morning walk through the Zhengyan terraces — ancient tea bushes growing from cracks in the cliff face|https://picsum.photos/800/1200?random=iwi003",

    ":::MAGAZINE_INTERVIEW_Q_A:::Chen|Your teas are known for their particularly strong yan yun — the rock character. What creates that quality?\n\nZhou|People always want a simple answer. They want me to say 'the minerals in the rock' or 'the microclimate of the gorge.' These things matter, but they are not the full answer. Yan yun is the sum of everything — the rock, yes, but also the age of the bushes, the specific cultivar, the water that seeps through the cliff face over centuries before reaching the roots, the morning fog that hangs in the gorge for hours, the afternoon sun that hits these terraces at a precise angle. And then there is the processing. I can take the same leaf and make it with more yan yun or less, depending on how I wither, how I oxidize, how I roast. The rock gives the potential. The tea maker decides how much of that potential reaches the cup.\n\nChen|How long does the roasting process take for your best teas?\n\nZhou|My Rou Gui receives three rounds of charcoal roasting. The first round is immediately after rolling — this is the mao huo, the rough fire, and it lasts about six hours. Then the tea rests for one month. The second round — the zu huo, the sufficient fire — is another four to six hours at a lower temperature. Another month of rest. The final round — the dun huo, the stewing fire — is gentle, maybe two to three hours, and its purpose is to marry all the flavors together and remove any remaining harshness. Total processing time from fresh leaf to finished tea: at minimum two months. For my best lots, three months.",

    ":::IMG_SPLIT_VERTICAL:::Left: Zhou's charcoal roasting room, bamboo baskets arranged over smoldering longan charcoal. Right: His weathered hands sorting finished leaves by grade|https://picsum.photos/800/1200?random=iwi004",

    ":::QUOTE_BIG:::The mountain does not hurry. Why should I? A tea made in haste carries that haste in its flavor. You can taste impatience.",

    ":::TEXT_SIDEBAR_IMAGE:::Zhou pauses our conversation to check on a batch of Shui Xian that has been withering since dawn. He lifts a handful of leaves, brings them close to his face, inhales deeply, then lets them fall back to the tray. 'Another two hours,' he says, and returns to his seat. This kind of interruption happens constantly during our visit. The tea takes priority over everything — conversation, meals, sleep. During peak harvest season, Zhou sleeps three to four hours a night for two weeks straight. 'The tea does not wait for you to be rested,' he says. 'When the leaf is ready, you must act. If you miss the moment by even an hour, the oxidation will be wrong and the whole batch suffers.'|https://picsum.photos/600/800?random=iwi005",

    ":::MAGAZINE_INTERVIEW_Q_A:::Chen|What concerns you about the future of Wuyi tea?\n\nZhou|Many things. The first is price speculation. The market for Zhengyan Yan Cha has become irrational. Some teas sell for prices that bear no relationship to their quality — they are status symbols, not beverages. This creates incentives for fraud. Tea from outside the Zhengyan zone is blended with Zhengyan tea and sold at Zhengyan prices. Consumers cannot tell the difference, and honest producers like me must compete with liars. The second concern is the next generation. My son studied computer science in Shanghai. He has no interest in returning to the mountain. I do not blame him — this life is hard, the income is uncertain, and young people want the comforts of the city. But if his generation does not come back, who will tend these gardens? The bushes are alive. They need care. You cannot abandon them for twenty years and then return to find the tea waiting for you.\n\nChen|Is there hope?\n\nZhou|Some. I see young people from the cities coming to learn. Not my own children, but other people's children. They are idealistic — they want to connect with the land, with tradition. Some of them stay. Most leave after one harvest season when they realize the romance is mostly mud and exhaustion. But the ones who stay, they learn quickly, and they bring new ideas. One young woman who trained with me for three years now runs her own small garden on the outer slopes. Her tea is good. Not yet great, but good. She has time.",

    ":::IMG_CIRCLE_MASK:::Zhou's hands — deeply lined, permanently stained by decades of handling charcoal and tea leaves|https://picsum.photos/800/800?random=iwi006",

    ":::MAGAZINE_INTERVIEW_Q_A:::Chen|What is the relationship between you and this mountain?\n\nZhou|[Long pause] It is not a relationship in the way you mean between two people. It is more like... I am part of the mountain. The mountain does not know I am here, not in the way a person knows. But I know the mountain in a way that is deeper than knowledge. I know where the water collects after rain. I know which cliff face catches the morning sun first. I know how the wind moves through the gorge in each season. I know the smell of the soil before and after rain. This knowing is in my body, not my mind. When I am away from the mountain — when I travel to Fuzhou or Shanghai for business — I feel physically wrong. My balance is different. My sleep is different. The water tastes wrong. I have become the mountain's creature, shaped by it over forty years the way the cliff shapes the root of the tea bush.\n\nChen|That is beautiful.\n\nZhou|It is not beautiful. It is simply true. Beauty is what visitors see when they come for a weekend. Truth is what remains when the visitors leave and the rain starts and you must carry thirty kilograms of fresh leaf down a wet stone path in the dark because the withering room is full and the leaves cannot wait.",

    ":::TEXT_DOUBLE_COL:::On Solitude|'People imagine that being a tea farmer is peaceful,' Zhou says as we walk the upper terraces in late afternoon light. 'And there are peaceful moments — early morning in the garden before the pickers arrive, late evening when the roasting is done and I sit with a cup of the day's production. But mostly it is worry. Worry about weather, about insects, about market prices, about whether the charcoal is the right temperature, about whether this batch will be as good as last year's. Solitude amplifies worry. There is no one to share the decisions with. If I misjudge the oxidation and ruin a batch, that is my failure alone. If the entire harvest is lost to an unseasonable frost, there is no one to commiserate with who truly understands.'\n\nOn Legacy|'I do not think about legacy in the way journalists want me to,' he continues. 'I think about this year's tea. Is it good? Is it honest? Does it express the mountain? If the answer is yes, then the legacy takes care of itself. The best memorial I could leave is not a famous name or a high price tag. It is a set of healthy bushes, well-tended soil, and the knowledge — carried in someone's hands, not just in their head — of how to bring out what the mountain has to offer.'",

    ":::IMG_WITH_CAPTION_BOTTOM:::Evening in the Wuyi Mountains — Zhou's workshop light glowing against the darkening cliff face as the final roasting of the day begins|https://picsum.photos/800/600?random=iwi007",

    ":::TEXT_JUSTIFIED_NARROW:::We left Zhou's workshop the following morning. He walked us to the road and waited until our car was out of sight before turning back to the mountain. On the drive to Wuyishan City, we opened a bag of his 2024 Rou Gui — the high-terrace lot he had given us as a parting gift. Even brewed in a hotel room with municipal water, it was extraordinary: deep amber liquor with a cinnabar sweetness, charcoal warmth, and beneath everything, the unmistakable minerality of the Zhengyan cliffs — the taste of the rock that Zhou calls home. The tea, like the man, was uncompromising, patient, and deeply rooted in its place.",

    ":::EPILOGUE_CENTERED:::Master Zhou Yu continues to produce some of Wuyi's finest Yan Cha from his family workshop in the Zhengyan zone. His teas are available in extremely limited quantities through a small number of trusted vendors. He does not sell online and has no plans to start. 'If the tea is good,' he says, 'people will find it.'",

    ":::COPYRIGHT_PAGE:::Interview by Chen Wei\nPhotography by Li Jun\nTeajia Journal — Voices in Tea"
  ],
  author: PEOPLE.chen,
  interviewee: PEOPLE.zhou,
};
