import { ContentType } from '../../types';
import { ReadableStory } from '../../types/read';
import { PEOPLE } from '../people';

export const longFormInterview: ReadableStory = {
  id: 'template-interview',
  type: ContentType.Article,
  status: 'published',
  title: 'Long-Form Interview',
  subtitle: 'A Conversation with Master Lin',
  thumbnailUrl: 'https://picsum.photos/800/1200?random=iv100',
  durationOrTime: '20 Pages',
  origin: 'In-house',
  description: 'An in-depth interview template featuring portraits, pull quotes, and extended Q&A format.',
  tags: ['Pottery', 'Teaware', 'Philosophy'],
  content: [
    ":::COVER_PHOTO_INSET:::Long-Form Interview|A Conversation with Master Lin|https://picsum.photos/800/1200?random=iv101",
    ":::TEXT_SINGLE_COL:::Master Lin's studio sits at the end of a dirt road on the outskirts of Dingshu, the pottery town that has been the center of Yixing purple clay teaware production for over five hundred years. The building is unremarkable from outside — a single-story concrete structure with a corrugated metal roof, indistinguishable from the dozens of small workshops that line the roads of this district. Inside, the air smells of damp earth and wood shavings. The walls are lined with wooden shelves holding hundreds of teapots in various stages of completion — some raw, some bisque-fired, some finished and gleaming with the deep, plummy luster that marks authentic zisha clay. Lin sits at a low workbench near the window, his hands wrapped around a cup of aged sheng puer. He is seventy-three years old, has been making teapots since the age of fourteen, and is recognized by the Chinese government as a Provincial-Level Master of Traditional Craft. He speaks slowly and precisely, with the quiet authority of someone who has nothing left to prove.",
    ":::MAGAZINE_INTERVIEW_Q_A:::Chen Wei|You come from a family of potters. How far back does the lineage go?|Master Lin|My grandfather's grandfather was already established in Dingshu by the mid-Qing dynasty — so perhaps seven or eight generations, depending on how you count. But I want to be honest about this. The unbroken lineage narrative is partly mythology. There were disruptions. My grandfather's kiln was destroyed during the Japanese occupation. My father was sent to a collective workshop during the Cultural Revolution, where he made factory teapots stamped with slogans instead of his own seal. The thread of transmission was thin at times. What survived was not technique — technique can be relearned from observation and practice. What survived was an attitude toward the clay. A way of listening to the material rather than imposing your will on it. That is the inheritance I received, and it cannot be written in a manual or taught in a school.",
    ":::IMG_SPLIT_VERTICAL:::Left: Lin's hands shaping a spout. Right: Shelves of finished work awaiting selection.|https://picsum.photos/800/1200?random=iv102",
    ":::MAGAZINE_INTERVIEW_Q_A:::Chen Wei|Describe your relationship with the clay itself. You've said before that you only use locally dug zisha. Why is that so important?|Master Lin|Zisha — purple sand clay — is not one material but a family of materials. The deposits around Yixing contain at least three major types: zini, the classic purple-brown; duanni, the pale golden variety; and zhuni, the rare vermillion clay. Within each type there are dozens of subtypes defined by mineral content, particle size, and firing characteristics. The clay I use comes from a deposit that my family has dug for generations. I know this clay the way a vintner knows their vineyard. I know that the layer at three meters depth fires to a cooler purple than the layer at five meters. I know that clay dug in autumn, after the summer rains have leached certain minerals, produces a different surface than clay dug in spring. Commercial clay — clay that has been machine-processed and blended for consistency — loses all of this specificity. It becomes a generic material. My clay is a specific material from a specific place, and the teapots I make from it carry the character of that place in their walls.",
    ":::QUOTE_BIG:::A teapot is not a container. It is a relationship between earth and water, mediated by fire and shaped by hand. Remove any element and you have an object. Include all four and you have something alive. — Master Lin",
    ":::TEXT_DOUBLE_COL:::The Workshop|Lin's working method is deliberately anachronistic. While many contemporary Yixing potters use plaster molds, electric wheels, and machine-mixed clay to increase production speed, Lin works entirely by hand using tools that his grandfather would recognize — bamboo paddles, wooden ribs, horn scrapers, and compass gauges made from bent wire. A single teapot takes him three to five days to complete, depending on complexity. His annual output is between forty and sixty pieces — a fraction of what a mold-using potter can produce in a month. This scarcity is not an affectation but a consequence of his method. Each pot is built from slabs of clay that are beaten, shaped, joined, and refined through dozens of incremental adjustments. The spout is not attached but grown from the body, the seam blended until it disappears. The lid is fitted so precisely that it can support the weight of the full pot when lifted — a test of craftsmanship that separates master work from competent production.\n\nThe Market|The economics of Yixing pottery have been transformed over the past two decades by a speculative market that treats master-crafted teapots as investment vehicles. Pots by nationally recognized masters can sell for six-figure sums, and a secondary market in authenticated vintage pieces rivals the art auction world in opacity and inflated valuation. Lin views this development with ambivalence. 'The money has brought attention and resources to the craft, which is good. Young people see a future in pottery again. But it has also created incentives for fraud — fake clay, forged seals, ghost-made pots attributed to famous names. And it has disconnected the pot from its purpose. A teapot that sits in a glass case as an investment has failed. A teapot succeeds only when it is used, when it absorbs the oils and tannins of ten thousand pourings, when it becomes seasoned and alive.'",
    ":::IMG_CIRCLE_MASK:::Portrait of Master Lin at his workbench|https://picsum.photos/800/800?random=iv103",
    ":::MAGAZINE_INTERVIEW_Q_A:::Chen Wei|You mentioned ghost-made pots. Can you explain that practice?|Master Lin|It is the worst-kept secret in Yixing. A famous master — someone with a national title and a recognizable seal — cannot possibly meet the demand for their work through their own hands alone. So they employ assistants or contract potters to make pots in their style, which the master then finishes, signs, and sells as their own. Some masters are honest about this — they acknowledge their studio produces collaborative work. Others are not. I have been approached many times to hire young potters and expand my output. I have always refused. When you buy a pot with my seal, every mark on it was made by my hands. This is my promise, and it is the only form of authentication that matters. Certificates and appraisals can be forged. The evidence of a single maker's hand, accumulated over sixty years of practice, cannot.",
    ":::IMG_FULL_BLEED:::A row of finished zisha teapots catching afternoon light|https://picsum.photos/800/1200?random=iv104",
    ":::MAGAZINE_INTERVIEW_Q_A:::Chen Wei|How do you think about innovation within a traditional craft? Is there room for experimentation in Yixing pottery?|Master Lin|This question assumes that tradition and innovation are opposites. They are not. Tradition is a river, not a wall. It flows. It changes course. It absorbs tributaries. The classic Yixing forms — Xishi, Fanggu, Shui Ping, Zhu Duan — were themselves innovations when they were first created. Someone looked at the existing vocabulary and added a new word. The question is not whether to innovate but how. Innovation that ignores the accumulated wisdom of the tradition is arrogance. Innovation that merely copies the tradition is cowardice. The narrow path between — where you understand the rules so deeply that you can break them meaningfully — that is where the interesting work happens. I have spent sixty years learning the rules. Only in the last ten have I felt qualified to break them. My recent work uses forms that no classical potter would recognize — asymmetric bodies, textured surfaces, deliberately imperfect lids. But the clay is the same. The method is the same. The hand is the same. The innovation is in the eye, not the technique.",
    ":::TEXT_SIDEBAR_LEFT:::On Seasoning|One of the most discussed aspects of Yixing teaware is the concept of seasoning — yanghu in Chinese, literally 'nourishing the pot.' Because zisha clay is porous, it absorbs the oils and compounds from each brewing. Over years of use, the pot develops a patina inside and out, and the tea brewed in it acquires a richness that a new pot cannot match. Lin is categorical on this point: 'One pot, one tea. Never brew different types of tea in the same pot. The clay will become confused. It will try to be everything and succeed at being nothing. Choose a tea for your pot — or let the pot choose its tea — and commit to that relationship for life. I have pots that have brewed nothing but aged puer for thirty years. The clay has become saturated. If you pour plain hot water into them, the water comes out tasting of tea. That is a pot that has achieved its purpose.'|https://picsum.photos/600/800?random=iv105",
    ":::IMG_FILM_STRIP_VERTICAL:::The making process: slab preparation, body forming, spout attachment, lid fitting|https://picsum.photos/800/400?random=iv106|https://picsum.photos/800/400?random=iv107|https://picsum.photos/800/400?random=iv108|https://picsum.photos/800/400?random=iv109",
    ":::TEXT_JUSTIFIED_NARROW:::As the afternoon light shifts in Lin's studio, he returns to his workbench and resumes work on a pot he started that morning — a small, round-bodied piece intended for Dancong oolong. He works in silence, his hands moving with a precision that looks effortless but represents six decades of motor learning. The bamboo paddle strikes the clay slab with a rhythm that is almost musical — tap, rotate, tap, rotate — gradually curving the flat sheet into a cylinder. He joins the edges with a slip of liquid clay, smoothing the seam with his thumb until it vanishes. Then he begins the compression, tapping the walls thinner and thinner, coaxing the cylinder into a sphere. The clay responds to his touch like a living thing, bulging where he pushes, thinning where he stretches, resisting only when he asks too much. Watching his hands, I understand what he means about listening to the material. The conversation between potter and clay is visible in every movement — a negotiation conducted in silence, resolved in form.",
    ":::MAGAZINE_INTERVIEW_Q_A:::Chen Wei|What advice would you give to a young person who wants to pursue Yixing pottery seriously?|Master Lin|First, learn to dig clay. Before you touch a tool, before you study form, go to the mines and understand where the material comes from. Hold the raw ore in your hands. Smell it. Taste it — yes, taste it. Learn to distinguish zini from duanni by feel alone. Second, find a teacher who will let you fail. The workshop system in Yixing has become too focused on producing competent copies. A good teacher will let you make ugly things, wrong things, broken things — and help you understand why they failed. My grandfather made me throw away my first two years of work. Every piece. He said: 'Those pots were made by your ambition. When you can make a pot with your patience, you will know.' Third, use your own pots. Brew tea in them every day. Live with their flaws. A potter who does not drink tea from their own work is like a cook who does not eat their own food — they have lost the connection between making and meaning.",
    ":::IMG_ARCH_MASK:::Master Lin's personal collection of seasoned pots, some over thirty years old|https://picsum.photos/800/1200?random=iv110",
    ":::QUOTE_BIG:::When you can make a pot with your patience, you will know.",
    ":::TEXT_SINGLE_COL:::We leave Lin's studio as the sun drops behind the kiln chimneys of Dingshu. The dirt road is quiet — most of the other workshops have closed for the day. In the distance, the sound of a television drifts from a farmhouse kitchen. Lin walks us to the gate and shakes hands with a grip that is surprisingly strong, the calluses on his palms rough against my skin. He does not say goodbye. He says: 'Come back in spring. The clay dug after the New Year rains is the best. I will show you.' It is an invitation, but also a statement of continuity. Spring will come. The rains will fall. The clay will be dug. The pots will be made. The river of tradition will flow on, carrying with it the accumulated knowledge of every hand that has ever shaped this extraordinary material. In Lin's workshop, that river runs deep and clear.",
    ":::EPILOGUE_CENTERED:::A master's hands speak\na language older than words.\nClay remembers everything.",
    ":::COPYRIGHT_PAGE:::Interview conducted by Chen Wei\nPhotography by Teajia Studios\nWith gratitude to Master Lin\nfor opening his workshop and his mind.\n\nTeajia Magazine"
  ],
  author: PEOPLE.chen,
  interviewee: PEOPLE.lin,
};
