import { ContentType } from '../../types';
import { ReadableStory } from '../../types/read';
import { PEOPLE } from '../people';

export const scientificReference: ReadableStory = {
  id: 'template-scientific',
  type: ContentType.Article,
  status: 'published',
  title: 'Scientific Reference Layout',
  subtitle: 'Camellia Sinensis Atlas',
  thumbnailUrl: 'https://picsum.photos/800/1200?random=sc100',
  durationOrTime: '23 Pages',
  origin: 'In-house',
  description: 'A systematic, botanical reference guide showcasing the scientific classification approach.',
  tags: ['Health', 'Teaching'],
  content: [
    ":::COVER_TYPOGRAPHIC:::CAMELLIA|SINENSIS|ATLAS",
    ":::TEXT_DROP_CAP:::The tea plant, Camellia sinensis, is a member of the family Theaceae, order Ericales — a flowering evergreen shrub or small tree native to the borderlands where modern China, Myanmar, Laos, and Vietnam converge. First described scientifically by Carl Linnaeus in 1753 as Thea sinensis, it was later reclassified into the genus Camellia by Robert Sweet in 1818, and the current binomial Camellia sinensis was formally adopted by Otto Kuntze in 1887. Despite its apparent simplicity as a single species, C. sinensis displays extraordinary morphological and chemical variation across its range, a diversity that has been amplified by centuries of human selection and cultivation. This atlas presents a systematic survey of the major varieties, cultivars, and chemotypes of C. sinensis, organized by botanical classification and geographic distribution, drawing on field observations from twelve tea-producing regions across six countries.",
    ":::TEXT_DOUBLE_COL:::Taxonomic Position|Kingdom: Plantae. Clade: Tracheophytes. Clade: Angiosperms. Clade: Eudicots. Clade: Asterids. Order: Ericales. Family: Theaceae. Genus: Camellia. Species: C. sinensis. The genus Camellia contains over 250 recognized species, of which C. sinensis is the only one widely cultivated for tea production. However, several related species — including C. taliensis, C. irrawadiensis, and C. grandibracteata — are used for tea in localized traditions, particularly among ethnic minority communities in Yunnan and northern Myanmar. These wild relatives represent an invaluable genetic reservoir for breeding programs aimed at developing disease resistance and climate adaptability.\n\nMajor Varieties|Two principal varieties are recognized: C. sinensis var. sinensis (the China type) and C. sinensis var. assamica (the Assam type). The China type is a small-leafed, cold-hardy shrub typically growing to 2-3 meters, with leaves 5-12 cm long and a compact, multi-stemmed growth habit. The Assam type is a large-leafed tropical tree that can reach 15-20 meters in the wild, with leaves 15-35 cm long and a single-trunk arboreal form. Between these two poles lies a continuum of intermediate forms — the Cambodian type (var. lasiocalyx), various wild Yunnan populations, and countless cultivated hybrids — that defy clean taxonomic categorization.",
    ":::TEXT_TRIPLE_COL:::Leaf Morphology|Tea leaves are alternate, simple, serrate, and coriaceous (leathery in texture). The leaf blade is elliptic to lanceolate, with an acute apex and cuneate base. Venation is pinnate, with 7-9 pairs of lateral veins at 45-80 degree angles to the midrib. The upper surface is glabrous and dark green; the lower surface may be pubescent, particularly along the midrib and veins in young leaves. Leaf size, shape, and serration pattern are the primary morphological markers used to distinguish cultivars in the field.\n\nFlower Structure|C. sinensis produces white to pale pink flowers, typically 2.5-4 cm in diameter, with 5-7 petals and a prominent central boss of yellow stamens. The flowers are bisexual and primarily insect-pollinated, though self-pollination is possible. Flowering occurs from October to February in the Northern Hemisphere. The fruit is a trilocular capsule containing 1-3 seeds, each approximately 1-1.5 cm in diameter with a hard, dark brown testa.\n\nRoot System|The root system of C. sinensis is characterized by a strong taproot that can penetrate 1.5-3 meters in well-drained soils, with extensive lateral root development in the upper 30-60 cm. Mycorrhizal associations are common and contribute significantly to nutrient uptake, particularly phosphorus. In ancient tea trees — specimens over 500 years old found in Yunnan — the root system may extend laterally up to 10 meters from the trunk, establishing a vast underground network that draws minerals from deep geological strata.",
    ":::BOTANICAL_SKETCH:::Camellia sinensis var. sinensis — leaf, flower, and seed capsule|https://picsum.photos/800/1000?random=sc101",
    ":::DEFINITION_LARGE:::Terroir|/tɛˈrwɑːr/|noun|The complete natural environment in which a tea is produced, including soil composition, altitude, slope aspect, microclimate, rainfall patterns, fog frequency, and surrounding vegetation. In Chinese tea culture, the equivalent concept is expressed through terms like shanchangwei (mountain field flavor) and diyunwei (earth rhyme flavor), which emphasize the inseparability of place and product.",
    ":::IMG_GRID_2x2:::Top left: var. sinensis leaf. Top right: var. assamica leaf. Bottom left: Wild Yunnan specimen. Bottom right: Cultivar cross-section.|https://picsum.photos/600/600?random=sc102|https://picsum.photos/600/600?random=sc103|https://picsum.photos/600/600?random=sc104|https://picsum.photos/600/600?random=sc105",
    ":::TEXT_SIDEBAR_RIGHT:::Chemical Composition|The young leaves and buds of C. sinensis contain an extraordinary array of bioactive compounds, the most significant being polyphenols (25-35% of dry weight), caffeine (2-5%), amino acids (1-5%, primarily L-theanine), and volatile aromatic compounds (0.01-0.02%). The polyphenol fraction is dominated by catechins — specifically epicatechin (EC), epicatechin gallate (ECG), epigallocatechin (EGC), and epigallocatechin gallate (EGCG). The relative proportions of these catechins vary significantly between varieties: var. assamica typically contains higher total catechin levels and a greater proportion of gallated catechins than var. sinensis, contributing to its more astringent flavor profile. L-theanine, an amino acid unique to Camellia and a few mushroom species, is responsible for the characteristic umami flavor of high-quality teas and has documented anxiolytic and neuroprotective properties.|https://picsum.photos/600/800?random=sc106",
    ":::IMG_WITH_CAPTION_BOTTOM:::Cross-section of a tea leaf under electron microscopy, showing trichomes, mesophyll layers, and vascular bundles|https://picsum.photos/800/600?random=sc107",
    ":::STAT_BIG_NUMBER:::3,000+|Registered cultivars of Camellia sinensis worldwide, with new selections being developed annually through controlled hybridization and clonal propagation programs",
    ":::TEXT_DOUBLE_COL:::Altitude and Chemistry|Research conducted across multiple tea-growing regions consistently demonstrates a positive correlation between cultivation altitude and tea quality, as measured by both chemical analysis and sensory evaluation. Teas grown above 1,200 meters typically show higher concentrations of L-theanine and aromatic compounds, with lower catechin-to-amino-acid ratios than lowland teas. The mechanisms are multiple: cooler temperatures slow leaf growth, allowing greater accumulation of flavor precursors; higher UV radiation stimulates production of protective phenolic compounds; greater diurnal temperature variation promotes synthesis of aromatic volatiles; and persistent fog reduces direct sunlight, suppressing catechin production while preserving amino acid levels. The net result is a tea with greater sweetness, more complex aroma, and less astringency — characteristics universally prized by connoisseurs.\n\nSoil and Mineral Uptake|The mineral composition of tea reflects the geology of its growing site with remarkable fidelity. Studies using inductively coupled plasma mass spectrometry (ICP-MS) have shown that the elemental fingerprint of a finished tea can be used to identify its geographic origin with over 90% accuracy. Key discriminating elements include manganese, aluminum, rare earth elements, and strontium isotope ratios. Tea plants are unusual hyperaccumulators of aluminum and manganese — elements that are toxic to most crops — and their ability to tolerate and even thrive in acidic, aluminum-rich soils (pH 4.5-5.5) is a defining ecological characteristic of the genus.",
    ":::TEXT_ASYMMETRIC_LEFT:::The Cultivar Landscape|Modern tea cultivation relies overwhelmingly on clonally propagated cultivars — genetically identical plants derived from cuttings of a single mother bush selected for desirable traits. In China alone, over 130 national-level approved cultivars are registered, with hundreds more at provincial and local levels. The most widely planted cultivar globally is probably TRFK 6/8, developed at the Tea Research Foundation of Kenya for high-yield CTC (crush-tear-curl) production. In China, the landscape is more diverse: Longjing 43 dominates the green tea regions of Zhejiang, Tieguanyin is the backbone of southern Fujian's oolong industry, and Yunnan's ancient forests contain wild and semi-wild populations that resist easy categorization into named cultivars. The tension between clonal uniformity and genetic diversity is one of the central challenges facing the tea industry. Clonal plantations offer predictability and yield, but they are vulnerable to disease epidemics and climate stress. Ancient seed-grown tea forests, with their heterogeneous genetics, offer resilience — but at the cost of consistency.",
    ":::BOTANICAL_SKETCH:::Comparative morphology: var. sinensis, var. assamica, and wild Yunnan type|https://picsum.photos/800/1000?random=sc108",
    ":::TEXT_SINGLE_COL:::The question of what constitutes a species, a variety, or a cultivar in Camellia is far from settled. Recent molecular phylogenetic studies using whole-genome sequencing have revealed that the traditional two-variety classification (sinensis vs. assamica) dramatically understates the genetic diversity within cultivated tea. Populations in western Yunnan, long classified as var. assamica based on leaf size alone, show greater genetic distance from Assam-type populations in India than either shows from var. sinensis. Some researchers have proposed recognizing a third variety — var. dehungensis — for these ancient Chinese populations. Others argue that the genus-level taxonomy itself needs revision, with some currently recognized species of Camellia potentially being conspecific with C. sinensis. The practical implications are significant: understanding the true genetic architecture of tea informs breeding strategies, conservation priorities, and our ability to predict how tea populations will respond to climate change.",
    ":::STAT_BIG_NUMBER:::~15,000 years|Estimated divergence time between var. sinensis and var. assamica based on whole-genome analysis, placing the split in the late Pleistocene",
    ":::TEXT_DOUBLE_COL:::Conservation Challenges|The ancient tea forests of Yunnan, Myanmar, and Laos represent one of the most significant reservoirs of Camellia genetic diversity on earth. Trees in these forests — some exceeding 1,000 years of age — contain alleles that have been lost from cultivated populations through centuries of selection for yield, flavor, and ease of processing. Yet these forests face mounting pressures: conversion to rubber and macadamia plantations, unregulated harvesting driven by speculative tea markets, and the slow attrition of traditional land management practices as younger generations migrate to cities. Several initiatives are underway to document and preserve this genetic heritage, including the Yunnan Ancient Tea Tree Census, which has cataloged over 54,000 individual ancient specimens across 15 prefectures.\n\nFuture Directions|Climate change is projected to shift the optimal growing zones for tea northward and upward in altitude by 100-500 meters over the coming decades. Some currently prime tea-growing regions — including parts of Assam, Sri Lanka, and Kenya — may become less suitable for high-quality production, while regions currently considered marginal — such as southern Europe, the Pacific Northwest of the United States, and highland regions of sub-Saharan Africa — may become newly viable. Genomic tools are being deployed to identify climate-adaptive traits in wild Camellia populations, with the goal of breeding cultivars that can maintain quality under warmer, more variable conditions. The race is on between a changing climate and our ability to understand and deploy the genetic resources that C. sinensis has accumulated over millions of years of evolution.",
    ":::COPYRIGHT_PAGE:::Text by Sarah Jenkins\nBotanical illustrations by the Teajia Studio\nScientific review by the Kunming Institute of Botany\n\nTeajia Magazine — Reference Series"
  ],
  author: PEOPLE.sarah,
};
