import { ContentType } from '../../types';
import { ReadableStory } from '../../types/read';
import { PEOPLE } from '../people';

export const timelineOverview: ReadableStory = {
  id: 'template-timeline',
  type: ContentType.Article,
  status: 'published',
  title: 'Timeline Overview',
  subtitle: 'Five Thousand Years of Tea',
  thumbnailUrl: 'https://picsum.photos/800/1200?random=tl100',
  durationOrTime: '19 Pages',
  origin: 'In-house',
  description: 'A chronological feature using timeline layouts, historical imagery, and era-by-era narrative.',
  tags: ['History', 'Origins', 'China'],
  startHere: true,
  content: [
    ":::COVER_MAIN:::Five Thousand Years|of Tea|https://picsum.photos/800/1200?random=tl101",

    ":::TEXT_DROP_CAP:::No other plant has shaped human civilization quite like Camellia sinensis. From its misty origins in the mountains of southwest China to its role as the catalyst for global trade wars, colonial empires, and cultural revolutions, tea has been a silent companion to nearly every major chapter of human history. It has been a medicine, a currency, a diplomatic tool, a spiritual practice, a symbol of resistance, and — above all — a daily ritual shared by billions. This is the story of that journey, told era by era, from the mythological age of Chinese emperors to the third-wave tea movement reshaping how we drink today. It is a story of monks and merchants, emperors and farmers, scientists and smugglers, and the quiet leaf that outlasted them all.",

    ":::LIST_TIMELINE:::2737 BCE — Emperor Shennong allegedly discovers tea when a leaf falls into his boiling water|59 BCE — Earliest written reference to tea as a purchased commodity, in Wang Bao's servant contract|220 CE — Tea becomes a daily drink among Chinese nobility during the Three Kingdoms period|760 CE — Lu Yu publishes 'Cha Jing' (The Classic of Tea), the first comprehensive tea treatise|780 CE — Tang Dynasty imposes the first tea tax, recognizing its economic importance|960 CE — Song Dynasty popularizes whisked powdered tea and competitive tea tasting|1391 — Ming Dynasty Emperor Zhu Yuanzhang bans compressed tea, mandating loose-leaf production|1610 — Dutch East India Company brings the first commercial tea shipment to Europe|1662 — Catherine of Braganza introduces tea to the English court|1773 — Boston Tea Party catalyzes the American Revolution|1823 — Robert Bruce discovers native tea plants in Assam, India|1848 — Robert Fortune smuggles tea plants and processing secrets from China to India|1869 — Suez Canal opens, dramatically reducing tea shipping times to Europe|1908 — Thomas Sullivan accidentally invents the tea bag in New York|2000s — Third-wave tea movement begins, emphasizing origin, craft, and single-estate teas",

    ":::TEXT_SINGLE_COL:::The earliest relationship between humans and the tea plant was almost certainly medicinal. In the subtropical forests of what is now Yunnan province, indigenous peoples chewed raw tea leaves for their stimulant and antimicrobial properties long before anyone thought to steep them in water. Archaeological evidence from the Han Dynasty (206 BCE–220 CE) confirms tea use in royal tombs, and chemical analysis of residues in ancient vessels has pushed confirmed tea consumption back at least 2,100 years. But the transition from medicine to beverage — from functional necessity to cultural practice — happened gradually over centuries, driven by Buddhist monks who found that tea aided meditation and by Taoist practitioners who associated the plant with longevity and spiritual clarity.",

    ":::CHAPTER_BOLD:::The Tang Dynasty|The Age of Lu Yu",

    ":::TEXT_DOUBLE_COL:::The Birth of Tea Culture|The Tang Dynasty (618–907 CE) transformed tea from a regional Chinese habit into a codified cultural practice with its own literature, aesthetics, and philosophy. At the center of this transformation stood Lu Yu, an orphan raised by Buddhist monks who became the most influential figure in tea history. His masterwork, 'Cha Jing' (The Classic of Tea), written around 760 CE, was the world's first comprehensive treatise on tea — covering everything from the botany of the plant to the ideal water sources, from the proper tools for preparation to the spiritual dimensions of the tea experience. Lu Yu elevated tea from a commodity to an art form, establishing principles that would guide tea culture for the next twelve hundred years.\n\nTang Dynasty Tea Practice|Tang-era tea was prepared by boiling compressed tea cakes that had been ground into powder, then whisked into the water along with salt and sometimes ginger or orange peel. The resulting brew was thick, savory, and worlds away from what we would recognize as tea today. It was served from large communal bowls and consumed in formal settings governed by elaborate etiquette. The Tang tea ceremony emphasized simplicity, natural beauty, and mindful attention — values that would later cross the sea to Japan and evolve into the Japanese tea ceremony (chanoyu). The Tang government recognized tea's growing cultural and economic significance by imposing the first tea tax in 780 CE, generating revenue that would fund military campaigns and infrastructure projects.",

    ":::IMG_FULL_BLEED:::Ancient tea trade routes through mountain passes|https://picsum.photos/800/1200?random=tl107",

    ":::IMG_DUOTONE:::A Song Dynasty tea competition painting reproduction|https://picsum.photos/800/600?random=tl108",

    ":::TEXT_SIDEBAR_RIGHT:::Song Dynasty Tea Competitions|The Song Dynasty (960–1279 CE) elevated tea appreciation to a competitive sport. 'Dou Cha' — tea competitions — were elaborate social events where participants judged each other's tea preparation technique. The goal was to produce the whitest, most persistent foam on the surface of whisked powdered tea. Judges evaluated color, consistency, fragrance, and the patterns formed by the foam. These competitions were not merely recreational — they drove innovation in tea cultivation, processing, and preparation that advanced the craft significantly. The emperor himself was a tea connoisseur; Emperor Huizong wrote a famous treatise on tea that detailed 20 categories of evaluation criteria.|https://picsum.photos/600/800?random=tl109",

    ":::QUOTE_BIG:::Tea began as a medicine and grew into a beverage. In China it became a form of art. In Japan, a religion of aesthetics. In England, a pretext for social gathering. In America, a reason for revolution.\n— Kakuzo Okakura, The Book of Tea",

    ":::IMG_WITH_CAPTION_BOTTOM:::A reproduction of a Ming Dynasty tea garden painting showing the transition to loose-leaf processing|https://picsum.photos/800/600?random=tl110",

    ":::TEXT_JUSTIFIED_NARROW:::The Ming Dynasty revolution of 1391 is one of the most consequential and least discussed moments in tea history. Emperor Zhu Yuanzhang, the founding ruler of the Ming Dynasty, issued an imperial decree banning the production of compressed tea cakes — the standard format for over a thousand years. His stated motivation was populist: compressed tea production was labor-intensive and associated with imperial luxury, while loose-leaf tea was simpler and more accessible to common people. The practical consequences were enormous. Without compressed cakes to grind and whisk, an entirely new preparation method was needed. The answer was infusion — steeping whole loose leaves in hot water and drinking the resulting liquor. This is the method we use today. In a single decree, Zhu Yuanzhang effectively invented modern tea drinking. The teapot, previously unnecessary, became essential. The gaiwan emerged as the ideal vessel for evaluating loose-leaf tea. And the extraordinary diversity of leaf shapes, sizes, and processing styles that we celebrate in modern tea culture became possible only because leaves were no longer destined to be ground into anonymous powder.",

    ":::MAP_CARTOGRAPHY:::Global Tea Trade Routes circa 1800|https://picsum.photos/800/600?random=tl111",

    ":::TEXT_SIDEBAR_LEFT:::The Great Tea Theft|In 1848, the British East India Company dispatched Scottish botanist Robert Fortune on one of history's most consequential acts of industrial espionage. Disguised as a Chinese merchant, Fortune traveled deep into Fujian and the Wuyi Mountains, collecting not only tea plant specimens but — critically — the closely guarded secrets of tea processing. He smuggled plants, seeds, and processing knowledge to British-controlled India, where the stolen material was used to establish tea plantations in Darjeeling and Assam. Within decades, Indian tea production rivaled and then surpassed Chinese output. China's millennium-long monopoly on tea was broken. The geopolitical consequences were profound: tea became a tool of British colonial power, with plantations established across India, Ceylon, and East Africa using systems of labor that ranged from exploitative to enslaving.|https://picsum.photos/600/800?random=tl112",

    ":::STAT_BIG_NUMBER:::6.3 Billion|Kilograms of tea produced globally in 2023",

    ":::TEXT_DOUBLE_COL:::The Industrial Revolution of Tea|The nineteenth and early twentieth centuries transformed tea from an artisanal product into an industrial commodity. The invention of the CTC (Crush, Tear, Curl) machine in 1930 by Sir William McKercher revolutionized black tea production, enabling factories to process huge volumes of leaf into uniform, small-particle tea optimized for consistent extraction in teabags. The tea bag itself, accidentally invented by New York merchant Thomas Sullivan in 1908, completed the industrialization by severing the consumer's connection to the whole leaf entirely. By the mid-twentieth century, most tea drinkers in the Western world had never seen a whole tea leaf, drinking only the anonymous dust and fannings packed into paper bags. Convenience had triumphed over craft, and tea entered a decades-long period of commodification.\n\nThe Third Wave|The third-wave tea movement, emerging in the early 2000s, represents a conscious rejection of tea's industrial period. Inspired by the specialty coffee movement's emphasis on origin, processing, and direct trade, third-wave tea culture celebrates the specific — this garden, this harvest, this maker's hand. Single-estate teas replaced anonymous blends. Gongfu brewing, with its emphasis on multiple short infusions, offered a method for experiencing the full complexity of high-quality leaf. Direct relationships between consumers and farmers, facilitated by the internet, bypassed the blending houses that had controlled tea distribution for centuries. Today, the third-wave movement continues to expand, driven by a generation of drinkers who approach tea with the same seriousness and curiosity that oenophiles bring to wine.",

    ":::TEXT_SINGLE_COL:::The story of tea is far from over. Climate change is reshaping tea-growing regions worldwide, pushing cultivation to higher altitudes and threatening traditional terroirs that have produced distinctive teas for centuries. Darjeeling's first-flush season has shifted earlier by nearly two weeks over the past three decades. Yunnan's ancient tea trees, some over a thousand years old, face unprecedented drought stress. Meanwhile, new tea regions are emerging in unexpected places — Nepal's high-altitude gardens are producing oolongs that rival Taiwan's best, and small-scale producers in Hawai'i, the Azores, and even Scotland are proving that Camellia sinensis is more adaptable than anyone imagined. The next chapter of tea's five-thousand-year story will be written not in the courts of emperors but in the gardens of a warming planet, by farmers and drinkers who must balance tradition with adaptation. The leaf endures. It always has.",

    ":::EPILOGUE_CENTERED:::From a single leaf in a mythical emperor's cup to six billion kilograms harvested annually across forty countries — tea's journey mirrors humanity's own. We have brewed it in clay pots over charcoal fires and in electric kettles in studio apartments. We have fought wars over it and found peace in it. And every morning, billions of us begin the day the same way our ancestors did five thousand years ago: with hot water and a leaf.",

    ":::COPYRIGHT_PAGE:::Teajia History"
  ],
  author: PEOPLE.chen,
};
