import { ContentType } from '../../types';
import { ReadableStory } from '../../types/read';
import { PEOPLE } from '../people';

export const travelJournalMaps: ReadableStory = {
  id: 'template-travel-journal',
  type: ContentType.Article,
  status: 'published',
  title: 'Travel Journal with Maps',
  subtitle: 'Ancient Tea Routes',
  thumbnailUrl: 'https://picsum.photos/800/1200?random=tj100',
  durationOrTime: '20 Pages',
  origin: 'In-house',
  description: 'A travelogue featuring cartographic illustrations, field observations, and cultural anthropology along historic tea trade routes.',
  tags: ['Culture', 'History'],
  content: [
    ":::COVER_SPLIT:::Travel Journal with Maps|Ancient Tea Routes|https://picsum.photos/800/1200?random=tj101",
    ":::MAP_CARTOGRAPHY:::The Tea Horse Road|Pu'er (Start)|Dali|Lijiang|Shangri-La|Markam|Chamdo|Lhasa (End)|Chengdu (Branch)|Kangding (Branch)",
    ":::TEXT_DROP_CAP:::The Chamagudao — the Tea Horse Road — is not a single road but a braided network of trails, passes, and river crossings that connected the tea-producing lowlands of Yunnan and Sichuan to the Tibetan Plateau and beyond for over a thousand years. At its peak during the Ming and Qing dynasties, this network carried an estimated ten million kilograms of compressed tea per year into Tibet, exchanged primarily for the war horses that Chinese dynasties needed to defend their northern borders against steppe nomads. The exchange ratio fluctuated with supply and demand but typically hovered around sixty kilograms of tea for one good horse — a price that reflected both the Tibetan addiction to butter tea and the Chinese military's insatiable appetite for cavalry mounts. I have spent the past three months tracing the southern route of the Tea Horse Road from its origin in the tea mountains of Xishuangbanna to its terminus in Lhasa, traveling by bus, by foot, and occasionally by mule, following paths that have been walked continuously for over thirteen centuries.",
    ":::TEXT_SINGLE_COL:::The journey begins in Pu'er City — formerly Simao, renamed in 2007 to capitalize on the global fame of its namesake tea. The city itself is unremarkable: a mid-sized Chinese municipality of concrete apartment blocks and wide boulevards, indistinguishable from a thousand others. But the surrounding countryside is the cradle of all tea. Within a hundred-kilometer radius lie the Six Famous Tea Mountains — Yibang, Gedeng, Mangzhi, Manzhuan, Mansa, and Youle — whose names appear in the earliest Qing dynasty records of tribute tea sent to the imperial court. These mountains, ranging from 1,200 to 1,800 meters in altitude, are covered in a patchwork of cultivated tea gardens, secondary forest, and fragments of old-growth rainforest. The tea here grows not in the manicured hedgerows of a modern plantation but in loose, semi-wild groves shaded by taller trees — a cultivation style that produces lower yields but richer, more complex leaf material. It is this leaf, compressed into dense cakes and bricks, that the Tea Horse Road was built to carry.",
    ":::POSTCARD_STYLE:::Day 7 — Yiwu Village|Dear reader — Arrived in Yiwu after six hours on a road that deserves the word 'road' only in the most generous interpretation. The village is tiny — perhaps fifty families — but its name carries immense weight in puer tea circles. Every second building is a tea processing workshop. The air smells of wood smoke and fermenting leaves. Bought a small cake of 2024 spring harvest from a family whose grandmother remembers the last horse caravans passing through in the 1950s. She said the mules knew the trail so well they could walk it without a driver. The drivers slept in the saddle. Price of the cake: more than I should have paid, less than it was worth.|https://picsum.photos/600/400?random=tj102",
    ":::NOTE_PAPER:::FIELD NOTES — Elevation: 1,640m — Weather: Fog, light rain\n\nObservations at the old caravan staging ground outside Yiwu:\n- Stone hitching posts still visible, worn smooth by centuries of rope\n- The trail width here is approximately 1.5 meters — wide enough for two loaded mules to pass\n- Paving stones (roughly cut limestone) visible beneath the mud in sections\n- Local informant (Mr. Yang, age 78) says his father was a mafuzi — a mule driver — who made the journey to Tibet four times before 1949\n- Each trip took approximately three months one way\n- A standard mule load was 60 jin (30 kg) of compressed tea\n- The caravans traveled in groups of 30-100 mules for protection against bandits\n- Payment was in silver or, on the return journey, in Tibetan horses, salt, and medicinal herbs",
    ":::IMG_FULL_BLEED:::The ancient stone trail descending from the tea mountains toward the Lancang River|https://picsum.photos/800/1200?random=tj103",
    ":::TEXT_SIDEBAR_RIGHT:::The Lancang Crossing|The first great obstacle on the southern Tea Horse Road is the Lancang River — known downstream as the Mekong. At the traditional crossing point near the town of Jinggu, the river runs through a gorge of red sandstone at approximately 600 meters elevation — a drop of over a thousand meters from the tea mountains above. The descent is brutal: a series of switchbacks carved into the cliff face, slippery with condensation from the river below. Loaded mules regularly fell to their death on this section, and the bones of animals and the shattered remains of tea bricks were said to litter the gorge bottom. Today, a modern suspension bridge spans the river at this point, but the old trail is still visible — a scar on the cliff face, overgrown with ferns and lianas but unmistakable in its purposeful, zigzagging descent. I walked it, unloaded and unburdened, and it took two hours. With a mule and thirty kilograms of tea, it would have been a full day's work.|https://picsum.photos/600/800?random=tj104",
    ":::TEXT_DOUBLE_COL:::Dali: The Crossroads|The walled city of Dali, capital of the ancient Nanzhao and Dali kingdoms, sits at the crossroads of the Tea Horse Road and the Burma Road, at the foot of the Cang Mountains on the shore of Erhai Lake. For centuries, it was the great trading hub of southwest China — a place where Tibetan horse traders, Yunnanese tea merchants, Burmese jade dealers, and Muslim caravaneers from Central Asia met to exchange goods, information, and culture. The old city retains much of its Ming dynasty layout: a grid of stone-paved streets enclosed by a partially intact wall with four gates oriented to the cardinal directions. The tea warehouses that once lined the main commercial street have mostly been converted to tourist shops and cafes, but in the back alleys of the Muslim quarter, a few traditional tea traders still operate from dim, fragrant storerooms stacked floor to ceiling with aged puer cakes wrapped in bamboo leaf packaging.\n\nI spent three days in Dali, visiting the remaining tea merchants and the Bai ethnic minority villages on the lakeshore where a distinctive style of roasted tea — sancha, or 'three-course tea' — is still served to guests as a gesture of hospitality. The three courses proceed from bitter to sweet to reflective: the first cup is a concentrated roasted green tea, intensely astringent; the second is the same tea sweetened with brown sugar, walnut, and sesame; the third is lightly flavored with honey and Sichuan pepper, leaving a tingling, contemplative finish. The Bai say this sequence mirrors the arc of life — bitterness, sweetness, and the complex aftertaste of experience.",
    ":::LIST_TIMELINE:::Tea Horse Road Timeline|618-907 CE: Tang Dynasty — first documented tea-horse trade between Sichuan and Tibet|960-1279 CE: Song Dynasty — formal Tea-Horse Office (Chama Si) established to regulate trade|1368-1644 CE: Ming Dynasty — peak of Tea Horse Road activity, with designated trading posts and government-set exchange rates|1644-1912 CE: Qing Dynasty — trade continues but gradually declines as maritime routes offer cheaper alternatives|1950s: Last mule caravans operate on the southern route before road construction makes them obsolete|2013: The Tea Horse Road is designated a National Key Cultural Heritage Protection Site",
    ":::IMG_SPLIT_VERTICAL:::Left: A restored section of stone-paved trail near Shaxi. Right: The last working blacksmith in Sideng, who once shod caravan mules.|https://picsum.photos/800/1200?random=tj105",
    ":::POSTCARD_STYLE:::Day 18 — Shangri-La (Zhongdian)|The altitude is starting to bite. At 3,300 meters, the air is thin enough to notice on the stairs to my guesthouse. The landscape has changed completely — the subtropical forests of the lowlands replaced by alpine meadows, yak pasture, and Tibetan Buddhist monasteries whose white walls and golden roofs gleam against impossibly blue skies. The tea here changes too. In the lowlands, people drink young sheng puer, bright and astringent. Here, they drink shou puer — dark, fermented, earthy — mixed with yak butter and salt in the Tibetan manner. The first time I tried butter tea, I thought it was soup. By the third cup, I understood: at this altitude, in this cold, this is not a beverage but a survival food. The fat provides calories, the salt replaces electrolytes, and the tea provides the caffeine needed to function in thin air. Form follows function, even in a teacup.|https://picsum.photos/600/400?random=tj106",
    ":::QUOTE_BIG:::The Tea Horse Road was not a road. It was a relationship — between lowland and highland, farmer and herder, leaf and hoof. When one end of the relationship died, the road died with it. — Professor Yang Haichao, Yunnan University",
    ":::TEXT_SINGLE_COL:::The most physically demanding section of the Tea Horse Road lies between Shangri-La and Markam, where the route crosses the Hengduan Mountains — a series of north-south ridges that form the eastern rampart of the Tibetan Plateau. The trail climbs over passes exceeding 4,500 meters, descends into gorges cut by the Yangtze, Mekong, and Salween rivers running in parallel channels barely fifty kilometers apart, then climbs again to the next pass. The vertical relief is staggering: in a single day's march, the caravan might descend 2,000 meters to a river crossing and climb 2,500 meters to the next camp. I did not attempt this section on foot — modern road conditions and altitude considerations made that impractical — but I traveled it by bus over four days, stopping at the small towns that grew up around the old caravan rest stations. At each stop, the cultural landscape shifted incrementally: the architecture becoming more Tibetan, the faces more weathered by altitude and wind, the tea darker and richer, the butter more rancid, the hospitality more insistent.",
    ":::IMG_WITH_CAPTION_BOTTOM:::The view from Baima Snow Mountain Pass (4,292m) — where the tea caravans crossed from Yunnan into Tibet|https://picsum.photos/800/600?random=tj107",
    ":::NOTE_PAPER:::FIELD NOTES — Day 24 — Markam, Tibet Autonomous Region\n\nCrossed the provincial border today. Everything changes.\n- Language: Mandarin gives way to Kham Tibetan\n- Architecture: Flat-roofed stone houses with prayer flags on every corner\n- Food: Tsampa (roasted barley flour), yak meat, butter tea exclusively\n- Tea preparation observed at a roadside station:\n  1. Black brick tea (shou puer) broken from a compressed brick with a knife\n  2. Boiled in water for 15-20 minutes (not steeped — boiled)\n  3. Poured into a dongmo (wooden churn) with a large lump of yak butter and a pinch of salt\n  4. Churned vigorously for 2-3 minutes until emulsified\n  5. Served in wooden bowls, refilled constantly — it is rude to let a guest's bowl sit empty\n- I drank approximately 15 bowls today. My hosts seemed pleased.",
    ":::TEXT_DOUBLE_COL:::The Economics of the Road|The Tea Horse Road was not a free market but a state-managed monopoly. From the Song dynasty onward, the Chinese government maintained a Tea-Horse Office that set exchange rates, controlled the volume of trade, and punished smuggling with severity. The logic was strategic: China needed horses for its military, Tibet needed tea for its diet, and the government needed to control both flows to maintain political leverage over the Tibetan kingdoms. Private merchants could participate in the trade only by purchasing government licenses and paying substantial taxes. The result was a system that enriched the state and the licensed merchants while leaving the actual laborers — the mule drivers, the porters, the tea farmers — in chronic poverty. The porters who carried tea over the mountain passes of western Sichuan were among the most exploited workers in Chinese history: men and women who carried loads of 150 kilograms or more on wooden frames strapped to their backs, climbing passes of 4,000 meters for wages that barely covered their food.\n\nThe Legacy|Today, the Tea Horse Road exists primarily as heritage tourism and branding. The Chinese government has designated significant sections as protected cultural sites, and several towns along the route — notably Shaxi, Lijiang, and Shangri-La — have been extensively restored (or reconstructed) to serve a growing domestic and international tourist market. Puer tea marketed with Tea Horse Road imagery commands premium prices, trading on the romance of the old caravan routes. But the actual trail — the stone-paved path worn smooth by ten million mule hooves — is disappearing. Sections are buried under highways, drowned by reservoir construction, or simply overgrown by the relentless subtropical vegetation. Within a generation, the physical road will exist only in fragments. What will survive is the idea of it: the image of a line drawn across the most extreme terrain on earth, connecting a leaf to a cup of butter tea, a lowland farmer to a highland herder, a civilization of agriculture to a civilization of pastoralism, joined by the simple, ancient, irreducible human need to trade.",
    ":::IMG_FULL_BLEED:::Prayer flags and compressed tea bricks at a roadside shrine near Chamdo|https://picsum.photos/800/1200?random=tj108",
    ":::EPILOGUE_CENTERED:::The road is gone.\nThe mules are gone.\nThe traders are gone.\n\nBut the tea still travels —\nby truck, by plane, by post —\nfrom the same mountains\nto the same plateau,\nfollowing the same need\nthat built the road\nin the first place.",
    ":::COPYRIGHT_PAGE:::Words and field notes by Chen Wei\nCartography by Teajia Studios\nHistorical consultation: Professor Yang Haichao,\nYunnan University Department of History\n\nTeajia Magazine — Travel Series"
  ],
  author: PEOPLE.chen,
};
