import { ContentType } from '../../types';
import { ReadableStory } from '../../types/read';
import { PEOPLE } from '../people';

export const travelFeatureVideo: ReadableStory = {
  id: 'template-travel-video',
  type: ContentType.Article,
  status: 'published',
  title: 'Travel Feature with Video',
  subtitle: 'Wuyi Mountains, Fujian',
  thumbnailUrl: 'https://picsum.photos/800/1200?random=tv100',
  durationOrTime: '18 Pages',
  origin: 'In-house',
  description: 'A multi-media travelogue featuring embedded video, atmospheric photography, and reportage from the Wuyi tea mountains.',
  tags: ['Oolong', 'China', 'Fujian', 'Sourcing'],
  content: [
    ":::COVER_MAIN:::Travel Feature with Video|Wuyi Mountains, Fujian|https://picsum.photos/800/1200?random=tv101",
    ":::TEXT_DROP_CAP:::The overnight train from Fuzhou arrives at Wuyishan North Station just before dawn. Outside the window, the landscape has already changed — the flat coastal plains have given way to something older and more vertical. Limestone karsts rise from the river valley like the petrified fingers of some ancient hand, their surfaces darkened by centuries of rain and mineral deposit. The air that rushes in when the doors open carries a dampness that feels botanical, thick with the exhalations of ten thousand species of fern and moss and lichen. This is the Wuyi Mountain UNESCO World Heritage Site, a place where geology and botany conspire to produce some of the most celebrated teas on earth. The locals call it yan yun — the rock rhyme — that ineffable mineral character that marks a true Wuyi oolong. I have come to understand where that flavor begins.",
    ":::IMG_FULL_BLEED:::Dawn breaks over the Nine Bend River, Wuyi Mountains|https://picsum.photos/800/1200?random=tv102",
    ":::TEXT_WITH_VIDEO:::Our first morning in the mountains begins with Master Zhou Yu, a third-generation tea maker whose family has tended plots along Huiyuan Keng — Wisdom Spring Ravine — since the 1940s. He meets us at the trailhead wearing rubber boots and carrying a bamboo basket slung over one shoulder. The path narrows quickly, winding between moss-covered boulders and beneath canopies of ancient camphor trees. Zhou walks with the ease of someone who has made this journey ten thousand times. He points to a cluster of tea bushes growing from a crack in the cliff face, their roots gripping the rock like talons. 'Rou Gui,' he says. 'Cassia bark. But here, because of this rock, this exact angle of sun, this specific drainage pattern — it becomes something else entirely. It becomes Huiyuan Keng Rou Gui. There is no other place on earth that produces this exact flavor.'|dQw4w9WgXcQ|Master Zhou guides us through Huiyuan Keng|The narrow ravine channels moisture and minerals to the tea bushes growing from the cliff walls.",
    ":::TEXT_SINGLE_COL:::The concept of terroir in tea mirrors that of wine, but in Wuyi it reaches an almost absurd level of specificity. Two bushes of the same cultivar planted fifty meters apart — one inside a named ravine, one on an open slope — will produce teas so different they might as well be separate varieties. The ravine teas, sheltered from direct sun, bathed in reflected light and constant humidity, develop a complexity and depth that open-slope teas simply cannot match. This is zhengyan — true rock tea — and it commands prices ten to fifty times higher than the same cultivar grown in the flatlands below. Zhou explains that his family tends just three named plots totaling less than two acres. The annual yield from these plots is measured in single-digit kilograms. Each kilogram represents not just labor but a relationship with a specific piece of stone that spans generations.",
    ":::TEXT_DOUBLE_COL:::The Ravines|Wuyi's named ravines — known as keng or jian — are the grand crus of Chinese oolong. The most famous include Niulan Keng (Bull Pen Ravine), Huiyuan Keng (Wisdom Spring Ravine), Liuxiang Jian (Flowing Fragrance Stream), Wuyuan Jian (Enlightenment Stream), and Daoshui Keng (Pouring Water Ravine). Together these form the core zhengyan production area, a territory of perhaps 70 square kilometers. Within this zone, microclimates shift dramatically with every turn of the path. North-facing slopes produce different tea than south-facing ones. Teas grown at the mouth of a ravine differ from those at its terminus. The Chinese concept of shan chang — mountain field — captures this specificity. Every plot has a name, a history, and a character.\n\nThe Processing|After picking, the leaves are spread on bamboo trays in the open air for initial withering. This solar withering lasts just long enough for the edges of the leaves to soften — Zhou watches for a slight loss of sheen on the leaf surface. Then the leaves are brought indoors for a process called zuoqing, alternating periods of shaking and resting that bruise the leaf edges and initiate oxidation. The shaking is done by hand in a large bamboo sieve, a rhythmic tossing motion that Zhou learned from his grandfather. 'The timing is everything,' he says. 'You watch the red edges spread. You smell the air change. When the fragrance shifts from green to floral, you stop.' The leaves are then fired in a wok to halt oxidation, rolled by hand into tight curls, and dried over charcoal — a process that may be repeated three or four times over the following months.",
    ":::QUOTE_BIG:::The mountain does not make the tea. The mountain makes the conditions. The tea makes itself. — Master Zhou Yu",
    ":::TEXT_WITH_VIDEO:::The charcoal roasting stage is where Wuyi oolong diverges most dramatically from other Chinese teas. While most oolongs receive a single light roast, Wuyi yancha undergoes multiple roasting sessions spread across several months. Zhou maintains a roasting room with a sunken pit filled with longan wood charcoal covered in a precise thickness of rice ash. The temperature is controlled not by thermometer but by hovering his palm over the ash surface. Each roasting session lasts six to eight hours, during which Zhou rotates bamboo baskets of tea over the heat source, occasionally lifting a basket to press his face into the warm leaves and inhale. He is reading the tea's progress through scent — tracking the departure of grassy notes, the emergence of caramel and stone fruit, the deepening of that signature mineral backbone. 'Roasting is a conversation,' he tells us. 'The fire speaks, and the tea answers. My job is to listen and know when to end the dialogue.'|dQw4w9WgXcQ|The art of charcoal roasting in Wuyi|Master Zhou demonstrates the traditional hongbei roasting method passed down through three generations.",
    ":::IMG_SPLIT_VERTICAL:::Left: Fresh leaves after picking. Right: After the third charcoal roast.|https://picsum.photos/800/1200?random=tv103",
    ":::TEXT_SINGLE_COL:::On our third day, Zhou takes us to see the mother trees — the original Da Hong Pao bushes that cling to a cliff face above Jiulong Ke, Nine Dragon Hollow. These six bushes, estimated to be over 350 years old, are the most famous tea plants in the world. They are surrounded by a stone wall and monitored by security cameras. The last harvest from these trees occurred in 2005, yielding just 20 grams of finished tea that was placed in the National Museum in Beijing. Standing below them, looking up at their gnarled trunks and sparse canopies, I feel the weight of the mythology that sustains this industry. Every Da Hong Pao sold today is a cutting descended from these six plants, propagated and replanted across the mountain. The original flavor — whatever it was — exists now only in memory and legend. What remains is the idea of it, the aspiration toward it, carried forward in every carefully roasted batch.",
    ":::IMG_CIRCLE_MASK:::Master Zhou Yu at the entrance to Huiyuan Keng|https://picsum.photos/800/800?random=tv104",
    ":::RECIPE_CARD:::Wuyi Yancha Gongfu Method|Vessel: 110ml gaiwan or Yixing clay pot.|Leaf: 8g (fill vessel 2/3 with dry leaf).|Water: 100°C — full boil, always.|Rinse: One quick wash, discard.|Steep 1-3: 10 seconds each.|Steep 4-6: 15 seconds each.|Steep 7+: Add 10 seconds per round.|Expect 8-12 quality steeps from true zhengyan material.",
    ":::TEXT_SIDEBAR_RIGHT:::Evening Sessions|Each night of our visit, Zhou hosts an informal tasting session on the wooden veranda of his farmhouse. The setup is simple — a clay tea tray, a kettle over charcoal, and a row of small white porcelain cups. He lines up four or five teas from the day's processing and pours them in silence. We taste without speaking, letting the liquor coat our tongues, breathing out through our noses to catch the retronasal aromatics. Only after everyone has tasted does the discussion begin. These sessions stretch past midnight, fueled by caffeine and the kind of unhurried conversation that seems possible only in places where the nearest city is three hours away. Zhou speaks about each tea the way a parent speaks about a child — with intimate knowledge, honest assessment, and unconditional pride.|https://picsum.photos/600/800?random=tv105",
    ":::MAP_CARTOGRAPHY:::Wuyi Mountain Tea Region|Niulan Keng|Huiyuan Keng|Liuxiang Jian|Wuyuan Jian|Daoshui Keng|Zhushao|Shuilian Dong",
    ":::TEXT_DOUBLE_COL:::The Economics|True zhengyan Wuyi oolong occupies a peculiar position in the global tea market. At the wholesale level, prices for premium Niulan Keng Rou Gui can exceed 10,000 RMB per jin (500 grams) — roughly $1,400 USD. At retail in major cities, the same tea might sell for triple that. Yet the farmers themselves often see only a fraction of the final price. Zhou is unusual in that he sells directly to a small network of collectors and tea shops, cutting out the middlemen who typically dominate the Wuyi market. 'I produce less than 40 kilograms of finished tea per year across all my plots,' he explains. 'I know every gram personally. I will not sell it to someone who will blend it with flatland tea and sell it under my ravine's name.'\n\nThe Future|The younger generation in Wuyi faces a choice familiar to rural artisans everywhere: continue the grueling work of mountain tea farming or seek easier livelihoods in the cities. Zhou's daughter studied agriculture at Fujian Normal University and has returned to help manage the family plots. She brings scientific rigor — soil testing, weather monitoring, controlled experiments with roasting parameters — while her father contributes the intuitive knowledge that no instrument can replicate. This combination, Zhou believes, is the future of Wuyi tea. 'The mountain does not change,' he says. 'But we must learn to speak its language in new ways.'",
    ":::IMG_FULL_BLEED:::The Nine Bend River winds through the heart of the Wuyi UNESCO Heritage Zone|https://picsum.photos/800/1200?random=tv106",
    ":::TEXT_SINGLE_COL:::On our final morning, we hike to the summit of Tianyou Peak — the Peak of Heavenly Travel. The trail is steep and slippery with morning dew. At the top, the entire Wuyi landscape unfolds beneath us: the dark ribbon of the Nine Bend River, the terraced tea gardens on every available slope, the scattered farmhouses with their clay-tiled roofs sending up threads of smoke from morning cooking fires. From this height, the karst peaks look less like geological formations and more like calligraphy — bold vertical strokes drawn by a cosmic brush across a green canvas. I think about Zhou's phrase, yan yun, the rock rhyme. Standing here, I finally understand that it refers not just to the flavor of the tea but to the rhythm of this entire landscape — the way stone and water and leaf and human effort rhyme together across centuries, producing something that transcends any single cup.",
    ":::COPYRIGHT_PAGE:::Words by Chen Wei\nPhotography by Li Jun\nWith gratitude to Master Zhou Yu\nand the tea farmers of Wuyi Mountain\n\nTeajia Magazine"
  ],
  author: PEOPLE.chen,
  interviewee: PEOPLE.zhou,
};
