/** Explicit correction verbs, all routed through the same preview/confirm gate. */
import { confirmCurateMutation, previewCurateMutation, previewCurateUndo, readCurateHistory, type CurateCommand } from '../curateMutations';
import type { ToolModule, ToolHandler } from './registry';
const base={entity:{type:'string',enum:['tea','vendor','note','transcript','attachment','todo','sample']},id:{type:'string'},agent:{type:'string'},confirmation_token:{type:'string',description:'Only supply after the user accepts the exact preview.'}};
const handle:ToolHandler=async(env,auth,args)=>{
 if(args?.confirmation_token) return confirmCurateMutation(env,auth,String(args.confirmation_token));
 return previewCurateMutation(env,auth,args as CurateCommand,typeof args?.agent==='string'?args.agent:'an agent');
};
export const curateManageModule:ToolModule={
 area:'curate management',
 defs:[
  {name:'curate_correct',scope:'stock:write',annotations:{destructiveHint:true},description:'Correct or clear shop Curate fields, remove a tasting term/score/photo, archive/delete a record, merge duplicates, or edit/close/delete a to-do, or taste a sample with explicit consumed grams. Every change previews first and requires explicit user acceptance before confirmation. Null clears nullable fields. Merge redirects the duplicate and preserves separate grams, physical holdings, sample histories and receipts. Shop owner or staff with explicit curate_manage permission only. Notes must belong to a tea in this shop; author attribution is preserved.',inputSchema:{type:'object',properties:{...base,action:{type:'string',enum:['edit','archive','delete','merge','close','reopen','remove_tasting','remove_score','remove_photo','taste_sample']},fields:{type:'object',description:'Only named fields change. Null explicitly clears a nullable field. Tea: name,chinese_name,type,form,year,season,storage,origin_country,origin_region,classification,cultivar,description,notes,shop_name,transport_mode,price_amount,price_currency,price_per_unit_grams,age_quoted,grade,pack_size_grams,pack_size_label,vendor_item_number,discount_percent,quote_id,route_quotes. Vendor: name,company,email,phone,whatsapp,address,city,country,notes. Note/transcript/todo: text. Sample: grams (finite nonnegative measured remaining weight, including zero; marks weight known without consuming it). Attachments: delete only; private asset bytes are retained.'},consumed_grams:{type:'number',minimum:0,description:'For taste_sample: grams actually consumed, explicitly zero if none. Never exceeds remaining sample grams; does not reduce real inventory.'},tasting:{type:'object',description:'Taxonomy term arrays for body,finish,feeling,flavor,liquor-color.'},score:{type:'integer',minimum:1,maximum:10},target_id:{type:'string'},category:{type:'string'},term:{type:'string'},photo:{type:'string',description:'Exact stored photo URL to remove from the tea; the asset is retained.'}},additionalProperties:false}},
  {name:'curate_history',scope:'inventory:read',description:'Read who changed which shop Curate records, what changed and when. Includes before/after snapshots and undo attribution.',inputSchema:{type:'object',properties:{entity_type:{type:'string',enum:['tea','vendor','note','transcript','todo','sample','quote','quote_line','attachment','asset','vendor_profile','sample_set','arrival']},entity_id:{type:'string'},limit:{type:'integer',minimum:1,maximum:100}},additionalProperties:false}},
  {name:'curate_undo',scope:'stock:write',annotations:{destructiveHint:true},description:'Preview undo of the shop\'s last confirmed Curate change. Confirm only after user acceptance. Refuses to overwrite newer edits or changed physical holdings. History remains append-only.',inputSchema:{type:'object',properties:{agent:base.agent,confirmation_token:base.confirmation_token},additionalProperties:false}},
 ],
 handlers:{curate_correct:handle,curate_history:async(env,auth,args)=>readCurateHistory(env,auth,args??{}),curate_undo:async(env,auth,args)=>args?.confirmation_token?confirmCurateMutation(env,auth,String(args.confirmation_token)):previewCurateUndo(env,auth,typeof args?.agent==='string'?args.agent:'an agent')},
};
