/**
 * migrate-articles — generate D1 migration SQL for the 5 chosen sample
 * articles, using parseStoryToBlocks. Run with:
 *
 *   node --experimental-strip-types scripts/migrate-articles.ts
 *
 * Outputs:
 *   worker/migrations/046_seed_articles.sql  (D1 INSERT OR REPLACE)
 *   scripts/migrate-articles.violations.json (over-budget content report)
 *
 * See docs/_archive/ARTICLE_UNIFICATION_PLAN.md.
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { parseStoryToBlocks, getViolations, clearViolations } from './parseDirectives.ts';

import { travelFeatureVideo } from '../src/content/articles/travel-feature-video.ts';
import { teaFeatureArticle } from '../src/content/articles/tea-feature-article.ts';
import { longFormInterview } from '../src/content/articles/long-form-interview.ts';
import { recipeAndPairing } from '../src/content/articles/recipe-and-pairing.ts';
import { originStory } from '../src/content/articles/origin-story.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, '..');

interface Pick {
  slug: string;
  story: { title: string; subtitle?: string; description?: string; thumbnailUrl?: string;
           author?: { name?: string; id?: string }; tags?: string[]; content?: string[] };
}

const ARTICLES: Pick[] = [
  { slug: 'travel-feature-video', story: travelFeatureVideo as never },
  { slug: 'tea-feature-article',  story: teaFeatureArticle as never },
  { slug: 'long-form-interview',  story: longFormInterview as never },
  { slug: 'recipe-and-pairing',   story: recipeAndPairing as never },
  { slug: 'origin-story',         story: originStory as never },
];

// SQL safety: D1 SQL strings need single-quote doubling. Newlines are fine
// inside D1 string literals. We don't need backslash escaping for SQLite.
function sqlEscape(s: string): string {
  return s.replace(/'/g, "''");
}

function authorSlug(story: Pick['story']): string | null {
  const a = story.author;
  if (!a) return null;
  if (a.id) return a.id;
  if (a.name) return a.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return null;
}

function readingTime(blocks: unknown[]): number {
  // Rough estimate: 200 words per minute, average 5 chars per word.
  const text = JSON.stringify(blocks);
  const chars = text.length;
  const minutes = Math.max(1, Math.round(chars / (200 * 5)));
  return minutes;
}

const lines: string[] = [];
lines.push('-- Migration 046: seed 5 sample articles into the new DbArticle system.');
lines.push('-- Generated by scripts/migrate-articles.ts. See docs/_archive/ARTICLE_UNIFICATION_PLAN.md.');
lines.push('-- Source articles in src/content/articles/ converted via scripts/parseDirectives.ts.');
lines.push('');

clearViolations();

for (const { slug, story } of ARTICLES) {
  const blocks = parseStoryToBlocks(story as never, slug);
  const cover = blocks.find(b => b.type === 'cover');
  const coverImage = (cover && 'image' in cover ? cover.image : undefined)
    ?? story.thumbnailUrl;

  const id = `art_${slug.replace(/-/g, '_')}`;
  const accountId = 'acc_teajia_bali';
  const title = story.title;
  const subtitle = story.subtitle ?? '';
  const author = authorSlug(story);
  const tags = JSON.stringify(story.tags ?? []);
  const blocksJson = JSON.stringify(blocks);
  const rt = readingTime(blocks);
  const publishedAt = '2026-04-25T00:00:00Z';
  const category = inferCategory(slug);

  lines.push(`-- ─── ${title} ───`);
  lines.push(
    `INSERT OR REPLACE INTO articles ` +
    `(id, account_id, title, subtitle, author_id, slug, status, category, tags, ` +
    `cover_image_url, blocks, reading_time_mins, published_at, created_at, updated_at) VALUES (`,
  );
  lines.push(`  '${id}',`);
  lines.push(`  '${accountId}',`);
  lines.push(`  '${sqlEscape(title)}',`);
  lines.push(subtitle ? `  '${sqlEscape(subtitle)}',` : `  NULL,`);
  lines.push(author ? `  '${sqlEscape(author)}',` : `  NULL,`);
  lines.push(`  '${slug}',`);
  lines.push(`  'published',`);
  lines.push(category ? `  '${category}',` : `  NULL,`);
  lines.push(`  '${sqlEscape(tags)}',`);
  lines.push(coverImage ? `  '${sqlEscape(coverImage)}',` : `  NULL,`);
  lines.push(`  '${sqlEscape(blocksJson)}',`);
  lines.push(`  ${rt},`);
  lines.push(`  '${publishedAt}',`);
  lines.push(`  datetime('now'),`);
  lines.push(`  datetime('now')`);
  lines.push(`);`);
  lines.push('');
}

function inferCategory(slug: string): string | null {
  if (slug.startsWith('tea-feature') || slug === 'travel-feature-video') return 'tea-feature';
  if (slug === 'long-form-interview') return 'interview';
  if (slug === 'recipe-and-pairing') return 'pairing';
  if (slug === 'origin-story') return 'curated';
  return null;
}

writeFileSync(join(repoRoot, 'worker/migrations/046_seed_articles.sql'), lines.join('\n'));

const v = getViolations();
writeFileSync(
  join(repoRoot, 'scripts/migrate-articles.violations.json'),
  JSON.stringify(v, null, 2),
);

console.log(`✓ Wrote worker/migrations/046_seed_articles.sql (${ARTICLES.length} articles)`);
console.log(`✓ Wrote scripts/migrate-articles.violations.json (${v.length} budget violations)`);
if (v.length > 0) {
  console.log('\nBudget violations:');
  for (const x of v.slice(0, 10)) {
    console.log(`  [${x.articleSlug} block ${x.blockIndex}] ${x.blockType}.${x.field}: ${x.actual}/${x.budget} chars — "${x.preview}"`);
  }
  if (v.length > 10) console.log(`  ... and ${v.length - 10} more`);
}
